import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/document_content.dart';

class DocumentLayoutService {
  /// Converts the structured DocumentModel into a PDF Document with proper pagination
  static Future<pw.Document> generatePdf(DocumentModel model) async {
    final pdf = pw.Document();
    
    // Global Settings
    final double baseFontSize = model.globalSettings['fontSize'] ?? 12.0;
    final double lineHeight = model.globalSettings['lineHeight'] ?? 1.5;
    final Map<String, dynamic> margins = model.globalSettings['margins'];

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.fromLTRB(
          margins['left'].toDouble(),
          margins['top'].toDouble(),
          margins['right'].toDouble(),
          margins['bottom'].toDouble(),
        ),
        header: (context) => _buildHeader(context, model),
        footer: (context) => _buildFooter(context, model),
        build: (context) => model.blocks.map((block) => _buildBlock(block, baseFontSize, lineHeight)).toList(),
      ),
    );

    return pdf;
  }

  static pw.Widget _buildBlock(DocumentBlock block, double baseSize, double spacing) {
    switch (block.type) {
      case DocumentNodeType.heading1:
        return pw.Header(
          level: 0,
          child: pw.Text(block.content, style: pw.TextStyle(fontSize: baseSize * 2, fontWeight: pw.FontWeight.bold)),
        );
      case DocumentNodeType.heading2:
        return pw.Header(
          level: 1,
          child: pw.Text(block.content, style: pw.TextStyle(fontSize: baseSize * 1.5, fontWeight: pw.FontWeight.bold)),
        );
      case DocumentNodeType.paragraph:
        return pw.Paragraph(
          text: block.content,
          style: pw.TextStyle(fontSize: baseSize, height: spacing),
        );
      case DocumentNodeType.bulletList:
        return pw.Bullet(text: block.content);
      default:
        return pw.SizedBox();
    }
  }

  static pw.Widget _buildHeader(pw.Context context, DocumentModel model) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(bottom: 20),
      child: pw.Text('Generated by DocAction', style: const pw.TextStyle(color: PdfColors.grey, fontSize: 10)),
    );
  }

  static pw.Widget _buildFooter(pw.Context context, DocumentModel model) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 20),
      child: pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(color: PdfColors.grey, fontSize: 10)),
    );
  }
}
