import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  // ✅ FIX 1: Add this method (for l10n access)
  static AppLocalizations of(BuildContext context) {
    return AppLocalizations(Localizations.localeOf(context));
  }

  // ✅ FIX 2: Add translate method
  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  // 🔽 KEEP YOUR EXISTING MAP BELOW (NO CHANGE)

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'rename': 'Rename',
      'export': 'Export',
      'move': 'Move',
      'delete': 'Delete',
      'my_scanner': 'My Scanner',
      'recent_captures': 'Recent\nCaptures',
      'search_docs': 'Search documents...',
      'scan_doc': 'Scan Document',
      'settings': 'Settings',
      'tools_hub': 'Tools Hub',
      'my_profile': 'My Profile',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'english_label': 'English',
      'hindi_label': 'Hindi',
      'app_lock': 'App Lock',
      'app_lock_sub': 'Biometric or PIN required to open',
      'pdf_quality': 'PDF Quality',
      'low_label': 'Low',
      'med_qual': 'Medium',
      'high_label': 'High',
      'sys_default': 'System Default',
      'light_label': 'Light',
      'dark_label': 'Dark',
      'version': 'Version',
      'preferences': 'Preferences',
      'privacy_policy': 'Privacy Policy',
      'read_terms': 'Read our terms and conditions',
      'privacy_intro':
          'Thank you for choosing DocAction. We are committed to protecting your personal information and your right to privacy.',
      'privacy_h1': '1. Information We Collect',
      'privacy_t1':
          'We only collect information that is necessary for the app to function. This includes:\n• Documents you scan (stored locally on your device).\n• Profile information (Name and Profile Photo) if you choose to set them.\n• App settings and preferences.',
      'privacy_h2': '2. Data Storage',
      'privacy_t2':
          'Your scanned documents and images are stored locally on your device\'s internal storage. We do not upload your documents to any external server unless you explicitly use a cloud-sync feature (if available).',
      'privacy_h3': '3. Permissions',
      'privacy_t3':
          'The app requires the following permissions to function:\n• Camera: To scan physical documents.\n• Storage: To save and load your scanned files.\n• Biometrics: To secure the app with App Lock.',
      'privacy_h4': '4. Data Security',
      'privacy_t4':
          'We take the security of your data seriously. By storing files locally and offering features like App Lock and PDF Encryption, we ensure that you remain in full control of your sensitive information.',
      'privacy_h5': '5. Changes to This Policy',
      'privacy_t5':
          'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.',
      'privacy_h6': '6. Contact Us',
      'privacy_t6':
          'If you have any questions about this Privacy Policy, please contact us at devopsaksentt@gmail.com',
      'security': 'Security',
      'exports': 'Exports',
      'data_management': 'Data Management',
      'optimize_library': 'Optimize Library',
      'reclaim_storage_sub': 'Reclaim storage & speed up app',
      'manage_deleted_docs': 'Manage recently deleted documents',
      'opt_desc':
          'This will compress all existing scans and generate faster thumbnails. This usually reduces storage usage by up to 90% and makes the app significantly snappier.\n\nThis process may take a minute depending on your library size.',
      'optimize_now': 'Optimize Now',
      'optimizing_library_msg': 'Optimizing Library...',
      'do_not_close_app': 'Please do not close the app',
      'opt_success': 'Library optimized successfully!',
      'opt_failed': 'Optimization failed',
      'about': 'About',
      'my_documents': 'My Documents',
      'recent_scans': 'Recent Scans',
      'recent_captures': 'Recent\nScans',
      'recycle_bin': 'Recycle Bin',
      'bin_empty_state': 'Recycle Bin is Empty',
      'deleted_items_hint': 'Deleted items will appear here',
      'empty_bin_title': 'Empty Recycle Bin?',
      'empty_bin_msg':
          'All documents in the recycle bin will be permanently deleted. This action cannot be undone.',
      'perm_delete': 'Permanently Delete',
      'undone_msg':
          'This document will be deleted forever. You cannot undo this action.',
      'logout': 'Logout',
      'login': 'Log In',
      'no_docs_msg': 'No documents yet.\nScan to get started!',
      'no_match_msg': 'No documents found matching your search.',
      'no_content_export': 'No content to export',
      'saved_to': 'Saved to: {0}',
      'export_failed': 'Export failed: {0}',
      'moved_items': 'Moved {0} {1}',
      'move_failed': 'Move failed: {0}',
      'item_label': 'item',
      'items_label': 'items',
      'documents': 'Documents',
      'tools': 'Tools',
      'profile': 'Profile',
      'selected': 'Selected',
      'unlock_biometrics': 'Unlock with Biometrics',
      'exit_app': 'Exit App',
      'scanner_locked': 'DocAction Locked',
      'auth_required': 'Authentication required to access files',
      'guest_user': 'Guest User',
      'sign_in_to_sync': 'Sign in to sync your scans',
      'login_signup': 'Sign In / Register',
      'new_folder': 'New Folder',
      'folder_name': 'Folder Name',
      'delete_folder': 'Delete Folder?',
      'delete_folder_msg': 'Items inside will be moved to the main library.',
      'doc_restored': 'Document restored successfully',
      'finalize_doc': 'Finalize Document',
      'draw_signature': 'Draw Signature',
      'create_signature': 'Create Signature',
      'scan_from_paper': 'Scan from Paper',
      'signature_weight': 'Weight',
      'clear_all': 'Clear All',
      'add_to_session': 'Add to Session',
      'save_signature': 'Save Signature',
      'draw_first_msg': 'Please draw a signature first!',
      'sig_saved_msg': 'Signature saved!',
      'incorrect_password_try_again': 'Incorrect password. Please try again.',
      'check_out_doc': 'Check out this document',
      'share_to_edit_label': 'SHARE TO EDIT',
      'extracted_data_label': 'EXTRACTED DATA',
      'text_copied_snack': 'Text copied to clipboard',
      'page_prefix': 'PAGE',
      'scan_err_msg': 'Scan error',
      'pdf_editor': 'PDF Editor',
      'annotate': 'Annotate',
      'shapes': 'Shapes',
      'insert': 'Insert',
      'hand_tool': 'Hand',
      'pen_tool': 'Pen',
      'marker_tool': 'Marker',
      'eraser_tool': 'Eraser',
      'text_tool': 'Text',
      'rectangle': 'Rectangle',
      'circle': 'Circle',
      'arrow': 'Arrow',
      'line': 'Line',
      'save_changes': 'Save Changes',
      'discard_changes': 'Discard Changes',
      'unsaved_changes_msg': 'You have unsaved changes. Discard?',
      'edit_pdf': 'Edit PDF',
      'pro_editor': 'Professional PDF Editor',
      'pro_editor_hint':
          'Draw, add text, shapes, or sign your documents with precision tools.',
      'select_pdf_to_edit': 'SELECT PDF TO EDIT',
      'highlight_tool': 'Highlight',
      'rect_label': 'Rect',
      'circle_label': 'Circle',
      'line_label': 'Line',
      'arrow_label': 'Arrow',
      'date_label': 'Date',
      'checkmark_label': 'Checkmark',
      'signature_label': 'Signature',
      'editing_selected': 'Editing Selected Element',
      'size_upper': 'SIZE',
      'opacity_upper': 'OPACITY',
      'select_document': 'Select Document',
      'grid_view': 'Grid',
      'list_view': 'List',
      'sort_by': 'Sort by: ',
      'sort_date': 'Date',
      'sort_name': 'Name',
      'sort_modified': 'Modified',
      'scan_prompt': 'What would you like to scan?',
      'scan_sub': 'Choose a mode for the best results',
      'mode_photo': 'PHOTO',
      'mode_id_card': 'ID CARD',
      'mode_document': 'DOCUMENT',
      'mode_ocr': 'OCR',
      'mode_qr': 'QR CODE',
      'mode_signature': 'SIGNATURE',
      'app_library': 'App Library',
      'library_hint': 'Choose from your scanned documents',
      'files_storage': 'Files / Storage',
      'storage_hint': 'Pick a PDF from your device storage',
      'save_document': 'Save Document',
      'document_name': 'Document Name',
      'edited_prefix': 'Edited',
      'edited_doc_default': 'Edited Document',
      'image_to_pdf': 'Image to PDF',
      'add_images': 'Add Images',
      'gallery_label': 'Gallery',
      'pick_from_library': 'Pick from Library',
      'library_empty_msg': 'Library is empty!',
      'edit_page': 'Edit Page',
      'convert_label': 'CONVERT',
      'pdf_gen_success': 'PDF Generated Successfully!',
      'page_size': 'Page Size:',
      'no_images_selected': 'No images selected',
      'add_from_gallery': 'ADD FROM GALLERY',
      'add_from_camera': 'ADD FROM CAMERA',
      'add_from_library': 'ADD FROM LIBRARY',
      'images_selected_count': '{0} Images selected',
      'pages_count': '{0} Pages',
      'generate_pdf': 'GENERATE PDF',
      'protect_pdf': 'Protect PDF',
      'lock_document': 'Lock your Document',
      'encryption_hint':
          'We use AES 256-bit encryption to ensure your data stays private and safe.',
      'file_locked': 'File is Locked',
      'file_protected_msg':
          'This document is already protected. Enter the current password to modify it.',
      'unlock_label': 'UNLOCK',
      'save_protected_pdf': 'Save Protected PDF',
      'protected_name_hint': 'Give your protected document a name:',
      'save_securely': 'SAVE SECURELY',
      'select_pdf_error': 'Please select a PDF file first',
      'enter_password_error': 'Please enter a password',
      'passwords_mismatch': 'Passwords do not match',
      'pdf_protected_success': 'PDF protected and saved as {0}',
      'set_password': 'Set Password',
      'confirm_password': 'Confirm Password',
      'strength_label': 'Strength: {0}',
      'min_chars_hint': 'Min. 6 chars',
      'protect_pdf_now': 'Protect PDF Now',
      'weak_label': 'Weak',
      'medium_label': 'Medium',
      'strong_label': 'Strong',
      'strength_none': 'None',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'unlock_pdf': 'Unlock PDF',
      'not_protected_error': 'This file is not password protected.',
      'pdf_unlocked_success': 'Document unlocked successfully!',
      'incorrect_password_try_again': 'Incorrect password. Please try again.',
      'unlock_failed': 'Unlock failed: {0}',
      'save_unlocked_pdf': 'Save Unlocked PDF',
      'save_unprotected_hint':
          'Save this document without password protection.',
      'save_now': 'SAVE NOW',
      'remove_protection': 'Remove Protection',
      'unlock_hint':
          'Upload a password-protected PDF to decrypt it and save a permanent copy without security.',
      'encrypted_doc': 'Encrypted Document',
      'unlocked_ready': 'Unlocked & Ready',
      'enter_password_to_unlock': 'Enter password to unlock',
      'verify_password': 'Verify Password',
      'save_unprotected_copy': 'Save Unprotected Copy',
      'organize_combine': 'Organize & Combine',
      'save_label': 'SAVE',
      'pdf_composition_saved': 'PDF Composition Saved!',
      'add_pdf': 'ADD PDF',
      'multi_file_organize': 'Multi-File Organize',
      'organize_hint':
          'Add one or more PDFs to rearrange and combine them visually.',
      'drag_interleave_hint': 'Drag to interleave pages from different files.',
      'pages_files_count': '{0} Pages • {1} Files',
      'select_source': 'Select Source',
      'choose_scanned_docs': 'Choose from your scanned documents',
      'pick_pdf_storage': 'Pick a PDF from your device storage',
      'no_pdf_error': 'Selected document doesn\'t have a PDF yet.',
      'page_organizer': 'Page Organizer',
      'arrange_pages': 'Arrange Pages',
      'reorder_hint': 'Long press and drag to reorder pages.',
      'start_adding_pages': 'Start Adding Pages',
      'add_pages_hint': 'Add pages from camera, scans, or files to organize.',
      'camera_label': 'Camera',
      'scans_label': 'Scans',
      'files_label': 'Files',
      'finalize_pdf': 'Finalize PDF',
      'finalize_hint':
          'Your organized pages will be saved as a new PDF document.',
      'filename_hint': 'Filename',
      'back_label': 'Back',
      'save_view': 'Save & View',
      'saved_downloads': 'Saved to Downloads',
      'saved_library': 'Saved to Library',
      'error_saving': 'Error saving PDF',
      'no_scans_found': 'No scans found in library',
      'add_from_scan': 'Add from Scans',
      'merged_doc_prefix': 'Organized',
      'page_of': 'Page {0} of {1}',
      'compress_pdf': 'Compress PDF',
      'compress_pdf_title': 'Reduce PDF Size',
      'compress_hint': 'Shrink PDF file size while maintaining visual quality.',
      'from_device_label': 'From Device',
      'from_library_label': 'From Library',
      'no_pdfs_library': 'No PDFs in Library!',
      'already_optimized': 'This file is already highly optimized!',
      'pdf_saved_msg': 'PDF Saved!',
      'compression_level': 'Compression Level',
      'recommended_level': 'Recommended',
      'recommended_desc': 'Best balance between size and quality',
      'extreme_level': 'Extreme',
      'extreme_desc': 'Maximum reduction (images will be resampled)',
      'basic_level': 'Basic',
      'basic_desc': 'Minimal reduction, preserves original data',
      'saved_percent_msg': '{0}% saved',
      'already_optimized_title': 'Already Optimized',
      'pdf_now_size': 'Your PDF is now {0} MB',
      'min_size_msg': 'File is already at its minimum size.',
      'before_label': 'Before',
      'after_label': 'After',
      'save_optimized_pdf': 'Save Optimized PDF',
      'save_anyway': 'Save Anyway',
      'split_pdf': 'Split PDF',
      'select_device': 'Select from Device',
      'select_device_sub': 'Browse your local PDF files',
      'select_app': 'Select from App',
      'select_app_sub': 'Choose from your scanned docs',
      'select_library': 'Select from Library',
      'no_pdfs_found': 'No PDFs found in your library yet!',
      'change_label': 'Change',
      'by_range': 'By Range',
      'extract_all': 'Extract All',
      'page_ranges': 'Page Ranges',
      'add_new_range': 'Add New Range',
      'from_label': 'From',
      'to_label': 'To',
      'zip_hint':
          'Every page will become a separate PDF. We will bundle them in a ZIP for you.',
      'extract_all_zip': 'Extract All & ZIP',
      'split_successful': 'Split successful! Saved to Library.',
      'extracted_multiple': 'Multiple files extracted! ZIP saved in Downloads.',
      'page_numbering': 'Page Numbering',
      'add_page_numbers': 'Add Page Numbers',
      'page_numbering_hint':
          'Select a PDF document to add\ncustomizable page numbers.',
      'numbered_pdf_saved': 'Numbered PDF saved successfully!',
      'cover_page_no_number': 'Cover page — no number',
      'skip_cover': 'Skip Cover',
      'format_label': 'FORMAT',
      'position_label': 'POSITION',
      'color_label': 'COLOR',
      'size_label': 'SIZE',
      'apply_label': 'Apply',
      'top_left': 'Top Left',
      'top_center': 'Top Center',
      'top_right': 'Top Right',
      'bottom_left': 'Bottom Left',
      'bottom_center': 'Bottom Center',
      'bottom_right': 'Bottom Right',
      'repair_pdf': 'Repair PDF',
      'repair_hint':
          'Fix corrupted or unreadable documents with our ultra-precise salvage engine.',
      'drop_corrupted_pdf': 'Drop Corrupted PDF',
      'repair_sub_hint': 'Fix broken structures & recover pages',
      'select_file_label': 'SELECT FILE',
      'healthy_status': 'HEALTHY',
      'corrupted_status': 'CORRUPTED',
      'verified_integrity': 'Verified Integrity',
      'structural_instability': 'Structural instability',
      'salvage_logs': 'SALVAGE LOGS',
      'engine_standby': 'Engine Standby',
      'salvaging_doc': 'SALVAGING DOCUMENT...',
      'repair_doc_label': 'REPAIR DOCUMENT',
      'repair_successful': 'Repair Successful',
      'repair_success_hint':
          'Internal structures stabilized and visual context salvaged.',
      'save_view_pdf': 'SAVE & VIEW PDF',
      'repair_another': 'Repair another file',
      'selected_label': 'Selected: {0}',
      'path_label': 'Path: {0}',
      'size_label_kb': 'Size: {0} KB',
      'empty_file_error': 'Error: Selected file is empty (0 bytes).',
      'empty_file_snack': 'The selected file is empty and cannot be repaired.',
      'healthcheck_error': 'Healthcheck: Structural corruption detected!',
      'no_pdf_version_error': 'Error: Selected document has no PDF version.',
      'file_not_found_error': 'Error: File not found at {0}',
      'library_file_empty_error': 'Error: Source file in library is empty.',
      'library_file_empty_snack':
          'The library file is empty and cannot be repaired.',
      'starting_repair_engine': 'Starting Advanced Repair Engine v2.0',
      'initializing_analysis': 'Initializing Analysis',
      'stabilizing_bytes': 'Stabilizing Bytes',
      'reconstructing_structure': 'Reconstructing Structure',
      'byte_stream_norm': 'Applying Stage 0: Byte-Stream Normalization...',
      'structural_repair': 'Applying Stage 1: Structural Repair...',
      'repair_success_log': 'Surgical repair successful. Integrity restored.',
      'fatal_recovery_error': 'Fatal Recovery Error: {0}',
      'structure_too_far_gone':
          'The document structure is too far gone for automatic salvage.',
      'repair_failed_snack': 'Repair Failed: {0}',
      'save_success_snack': 'Success! PDF saved to library and Downloads.',
      'save_failed_log': 'Save failed: {0}',
      'pdf_to_image': 'PDF to Image',
      'init_conversion': 'Initializing conversion...',
      'extracted_page': 'Extracted Page {0}',
      'images_from_label': 'Images from {0}',
      'extracted_images_count_log': 'Extracted {0} images from PDF.',
      'extract_success_snack':
          'Successfully extracted {0} images! Saved to home.',
      'extract_error_snack': 'Extraction Error: {0}',
      'select_pdf_doc': 'Select PDF Document',
      'extract_photos_hint': 'Extract pages as high-quality photos',
      'extract_as_images': 'EXTRACT AS IMAGES',
      'extraction_quality': 'EXTRACTION QUALITY',
      'standard_label': 'Standard',
      'hd_label': 'HD',
      'ultra_label': 'Ultra',
      'fast_conversion': 'Fast conversion',
      'great_balance': 'Great balance',
      'print_ready': 'Print ready',
      'pdf_to_word': 'PDF to Word',
      'converting_pdf_to_word': 'Converting PDF to Word...',
      'extracting_text_doc': 'Extracting text and building document',
      'conversion_success': 'Conversion successful!',
      'conversion_error_snack': 'Conversion Error: {0}',
      'share_error_snack': 'Share Error: {0}',
      'save_to_library_success': 'Saved to Library!',
      'save_error_snack_param': 'Save Error: {0}',
      'choose_source': 'CHOOSE SOURCE',
      'repair_pdf': 'Repair PDF',
      'repair_hint':
          'Fix corrupted or unreadable documents with our ultra-precise salvage engine.',
      'drop_corrupted_pdf': 'Drop Corrupted PDF',
      'repair_sub_hint': 'Fix broken structures & recover pages',
      'select_file_label': 'SELECT FILE',
      'healthy_status': 'HEALTHY',
      'corrupted_status': 'CORRUPTED',
      'verified_integrity': 'Verified Integrity',
      'structural_instability': 'Structural instability',
      'salvage_logs': 'SALVAGE LOGS',
      'engine_standby': 'Engine Standby',
      'salvaging_doc': 'SALVAGING DOCUMENT...',
      'repair_doc_label': 'REPAIR DOCUMENT',
      'repair_successful': 'Repair Successful',
      'repair_success_hint':
          'Internal structures stabilized and visual context salvaged.',
      'save_view_pdf': 'SAVE & VIEW PDF',
      'repair_another': 'Repair another file',
      'selected_label': 'Selected: {0}',
      'path_label': 'Path: {0}',
      'size_label_kb': 'Size: {0} KB',
      'empty_file_error': 'Error: Selected file is empty (0 bytes).',
      'empty_file_snack': 'The selected file is empty and cannot be repaired.',
      'healthcheck_error_log': 'Healthcheck: Structural corruption detected!',
      'no_pdf_version_error': 'Error: Selected document has no PDF version.',
      'file_not_found_error': 'Error: File not found at {0}',
      'library_file_empty_error': 'Error: Source file in library is empty.',
      'library_file_empty_snack':
          'The library file is empty and cannot be repaired.',
      'imported_label': 'Imported',
      'healthcheck_error': 'Healthcheck: Structural corruption detected!',
      'starting_repair_engine': 'Starting Advanced Repair Engine v2.0',
      'byte_stream_norm': 'Applying Stage 0: Byte-Stream Normalization...',
      'structural_repair': 'Applying Stage 1: Structural Repair...',
      'repair_success_log': 'Surgical repair successful. Integrity restored.',
      'fatal_recovery_error': 'Fatal Recovery Error: {0}',
      'structure_too_far_gone':
          'The document structure is too far gone for automatic salvage.',
      'repair_failed_snack': 'Repair Failed: {0}',
      'repaired_doc_prefix': 'Repaired',
      'save_success_snack': 'Success! PDF saved to library and Downloads.',
      'repaired_document': 'Repaired Document',
      'save_failed_log': 'Save failed: {0}',
      'initializing_analysis': 'Initializing Analysis',
      'stabilizing_bytes': 'Stabilizing Bytes',
      'reconstructing_structure': 'Reconstructing Structure',
      'idle': 'Idle',
      'ready': 'Ready',
      'pick_from_device': 'Pick from Device',
      'pick_pdf_storage': 'Pick a PDF from your device storage',
      'app_library': 'App Library',
      'choose_scanned_docs': 'Choose from your scanned documents',
      'cancel_label': 'CANCEL',
      'save_label': 'SAVE',
      'filename_hint': 'Filename',
      'pdf_composition_saved': 'PDF Composition Saved!',
      'pick_word_storage': 'Pick Word from device storage',
      'choose_saved_word': 'Choose from your saved documents',
      'not_word_file_error': 'Selected file is not a Word document',
      'converting_msg': 'Converting Word to PDF...',
      'success_saved_lib': 'Success! Saved to Library.',
      'word_convert_error': 'Conversion failed: {0}',
      'organized_doc_prefix': 'Organized',
      'select_source': 'Select Source',
      'add_pdf': 'ADD PDF',
      'multi_file_organize': 'Multi-File Organize',
      'organize_hint':
          'Add one or more PDFs to rearrange and combine them visually.',
      'drag_interleave_hint': 'Drag to interleave pages from different files.',
      'pages_files_count': '{0} Pages • {1} Files',
      'organize_combine': 'Organize & Combine',
      'from_device': 'From Device',
      'from_library': 'From Library',
      'browse_files': 'Browse your local files',
      'system_photos': 'Pick images from gallery',
      'my_scans': 'My Scans',
      'internal_app_scans': 'Choose from scanned docs',
      'select_scans': 'Select Scans',
      'enter_password_hint': 'Enter password',
      'enter_name': 'Enter name',
      'incorrect_password': 'Incorrect password. Please try again.',
      'error_prefix': 'Error',
      'pdf_locked_error': 'PDF is password protected and cannot be organized.',
      'pick_from_device': 'Pick from Device',
      'browse_local_files': 'Browse your local files',
      'from_library_sub_hint': 'Select a saved document',
      'convert_to_editable_word': 'Convert to Editable Word',
      'convert_word_hint':
          'Turn any PDF into a (.docx) file locally while preserving text content.',
      'conversion_complete': 'Conversion Complete!',
      'convert_another': 'CONVERT ANOTHER',
      'share_docx': 'SHARE DOCX',
      'save_to_library_btn': 'SAVE TO LIBRARY',
      'converted_word_doc': 'Converted Word Document',
      'converted_label': 'Converted',
      'text_to_pdf': 'Text to PDF',
      'enter_text_snack': 'Please enter some text to convert',
      'text_doc_default_name': 'Text Document {0}_{1}_{2}',
      'save_pdf_doc_title': 'Save PDF Document',
      'assign_name_hint': 'Assign a name for your text document',
      'name_label': 'Name',
      'cancel_label': 'CANCEL',
      'generate_save_btn': 'GENERATE & SAVE',
      'converted_text_title': 'Converted Text',
      'text_imported_snack': 'Text imported from scan',
      'clear_text_title': 'Clear Text?',
      'clear_text_hint': 'This will remove all text from the editor.',
      'clear_label': 'CLEAR',
      'clear_all_tooltip': 'Clear all text',
      'scan_text_tooltip': 'Scan text from camera',
      'type_paste_hint': 'Start typing or paste your content here...',
      'converting_label': 'CONVERTING...',
      'convert_to_pdf_btn': 'CONVERT TO PDF',
      'word_to_pdf': 'Word to PDF',
      'word_doc_default_name': 'Word_Doc_{0}_{1}_{2}',
      'assign_converted_name_hint': 'Assign a name for your converted document',
      'convert_save_btn': 'CONVERT & SAVE',
      'converted_from_word_log': 'Converted from Word: {0}',
      'select_word_doc': 'Select Word Document',
      'tap_to_change_file': 'Tap to change file',
      'supported_format_docx': 'Supported format: .docx',
      'folder_content': 'Folder Content',
      'back_to_library': 'Back to Library',
      'rename_doc': 'Rename Document',
      'enter_new_name': 'Enter new name',
      'move_to_folder': 'Move to Folder',
      'root_documents': 'Root Documents',
      'delete_forever': 'Delete Forever',
      'create': 'Create',
      'cancel': 'Cancel',
      'save': 'Save',
      'add_from_scan': 'Add from Scans',
      'no_scans_found': 'No scans found in library',
      'select_images_library': 'Select Images from Library',
      'no_images_in_doc': 'This document contains no images',
      'edit_page': 'Edit Page',
      'id_card_scanner': 'ID Card Scanner',
      'choose_scan_type': 'Choose Scan Type',
      'select_scan_method_hint': 'Select how you want to scan your ID card',
      'single_side': 'Single Side',
      'single_side_hint': 'Scan only the front of the ID card',
      'double_side': 'Double Side',
      'double_side_hint': 'Capture both front and back correctly',
      'front_side_editor': 'Front Side Editor',
      'back_side_editor': 'Back Side Editor',
      'capture_front_snack': 'Capture the front side first!',
      'capture_back_snack': 'Capture the back side first!',
      'id_card_save_success': 'ID Card saved successfully!',
      'both_sides_scan': 'Both Sides Scan',
      'single_side_scan': 'Single Side Scan',
      'front_side': 'Front Side',
      'back_side': 'Back Side',
      'tap_to_capture': 'Tap to Capture',
      'finalize_save': 'Finalize & Save',
      'ocr_result': 'OCR Result',
      'text_copied_snack': 'Text copied to clipboard',
      'recognized_text_hint': 'Recognized text will appear here...',
      'copy_label': 'COPY',
      'share_label': 'SHARE',
      'save_ocr_result_title': 'Save OCR Result',
      'doc_name_label': 'Document Name',
      'saved_to_docs_snack': 'Saved to your documents!',
      'document_pages': 'Document Pages',
      'ocr_error_prefix': 'OCR Error: {0}',
      'page_prefix': 'Page',
      'add_page_btn': 'Add Page',
      'extract_text_btn': 'Extract Text',
      'add_custom_size': 'Add Custom Size',
      'select_source': 'Select Source',
      'from_device': 'From Device',
      'from_device_sub': 'Pick files from internal storage',
      'from_library': 'From Library',
      'from_library_sub': 'Choose from scanned documents',
      'extraction_quality': 'Extraction Quality',
      'standard_label': 'Standard',
      'fast_conversion': 'Fast Conversion',
      'hd_label': 'HD',
      'great_balance': 'Great Balance',
      'ultra_label': 'Ultra',
      'print_ready': 'Print Ready',
      'extract_as_images': 'Extract as Images',
      'images_from_label': 'Images from {0}',
      'extract_success_snack': 'Successfully extracted {0} images!',
      'extract_error_snack': 'Extraction Error: {0}',
      'init_conversion': 'Initializing conversion...',
      'extracted_page': 'Extracted page {0}',
      'extracted_images_count_log': 'Extracted {0} images from PDF',
      'label_hint': 'Label (e.g. My Visa)',
      'width_label': 'Width',
      'height_label': 'Height',
      'cancel_btn': 'Cancel',
      'add_btn': 'Add',
      'select_id_photo_size': 'Select ID Photo Size',
      'custom_size_card': 'Custom Size',
      'photo_size_passport': 'Passport',
      'photo_size_visa_us': 'Visa (US)',
      'photo_size_id_card': 'ID Card',
      'photo_size_pan_card': 'Pan Card',
      'photo_size_driving_license': 'Driving License',
      'session_organizer': 'Session Organizer',
      'capture_more': 'Capture More',
      'save_exit': 'Save & Exit',
      'photos_saved_home': 'ID Photos saved to Home Screen!',
      'scan_result': 'Scan Result',
      'open_link': 'Open Link',
      'call_label': 'Call',
      'send_email': 'Send Email',
      'could_not_open_link': 'Could not open link',
      'open_in_browser': 'Open in Browser',
      'search_web': 'Search Web',
      'sig_min_one_snack': 'Please capture or draw at least one signature.',
      'sig_pack_saved_snack': 'Signature Pack saved!',
      'tap_to_edit': 'Tap to Edit',
      'scan_more': 'Scan More',
      'draw_new': 'Draw New',
      'save_sig_pack': 'Save Signature Pack',
      'scan_history': 'Scan History',
      'clear_all': 'Clear All',
      'clear_history_dialog': 'Clear History',
      'clear_history_confirm':
          'Are you sure you want to delete all scan history?',
      'no_scan_history': 'No scan history yet',
      'no_scan_history_sub': 'Your scanned QR and Barcodes will appear here.',
      'doc_signed_saved_snack': 'Document signed and saved!',
      'save_doc_as': 'Save Document As',
      'enter_signed_pdf_name': 'Enter a name for your signed PDF:',
      'filename_hint': 'Filename',
      'enter_text': 'Enter Text',
      'my_signatures': 'My Signatures',
      'no_saved_signatures': 'No saved signatures yet.',
      'sign_document': 'Sign Document',
      'done_btn': 'Done',
      'sign_label': 'Sign',
      'text_label': 'Text',
      'date_label': 'Date',
      'prev_label': 'Prev',
      'next_label': 'Next',
      'manual_crop': 'Manual Crop',
      'crop_to_size': 'Crop to {0}',
      'size_crop': 'Size Crop',
      'grayscale_label': 'Grayscale',
      'id_specialized_cat': 'ID & SPECIALIZED',
      'id_card_title': 'ID Card Scanner',
      'id_card_sub': 'Scan and digitize your ID cards',
      'id_photo_title': 'ID Photo Maker',
      'id_photo_sub': 'Create passport size photos',
      'signature_tool_title': 'Digital Signature',
      'signature_tool_sub': 'Create and save your signature',
      'qr_tool_title': 'QR & Barcode',
      'qr_tool_sub': 'Scan or generate QR codes',
      'ai_smart_cat': 'AI & SMART TOOLS',
      'ocr_title': 'OCR (Text Extract)',
      'ocr_sub': 'Extract text from images instantly',
      'ai_chat_title': 'AI Doc Chat',
      'ai_chat_sub': 'Chat with your documents',
      'rename_doc': 'Rename Document',
      'enter_new_name': 'Enter new name',
      'save_to_device': 'Save PDF to device',
      'move_to_folder': 'Move to Folder',
      'back_to_library': 'Back to Library',
      'library_empty': 'Your library is empty',
      'start_scanning': 'Start scanning to build your collection',
      'no_results': 'No results found',
      'try_different_term': 'Try a different search term',
      'change_name': 'Change Name',
      'choose_profile_pic': 'Choose Profile Picture',
      'remove_profile_pic': 'Remove Profile Picture',
      'crop_profile_pic': 'Crop Profile Picture',
      'profile_pic_updated': 'Profile picture updated!',
      'failed_pick_image': 'Failed to pick image',
      'storage': 'Storage',
      'scanning_history': 'Scanning History',
      'help_support': 'Help & Support',
      'login_subtitle': 'Sign in to your account',
      'login_success': 'Login successful!',
      'storage_usage': 'Storage Usage',
      'local_storage': 'Local Storage',
      'cloud_storage': 'Cloud Storage',
      'not_configured': 'Not configured',
      'space_left_msg': 'You have plenty of space left for new scans!',
      'contact_us_msg':
          'Having issues with DocAction?\n\nPlease contact us at devopsaksentt@gmail.com',
      'not_logged_in': 'Not Logged In',
      'signin_register': 'Sign In / Register',
      'profile_name_updated': 'Profile name updated!',
      'edit_profile_name': 'Edit Profile Name',
      'enter_your_name': 'Enter your name',
      'save': 'Save',
      'cancel': 'Cancel',
      'create': 'Create',
      'organize_pdf': 'Organize PDF',
      'optimize_pdf': 'Optimize PDF',
      'convert_pdf': 'Convert PDF',
      'edit_pdf_cat': 'Edit PDF',
      'security_cat': 'Security',
      'merge_title': 'Merge',
      'merge_sub': 'Join PDFs into one',
      'split_title': 'Split',
      'split_sub': 'Extract pages',
      'reorder_title': 'Reorder',
      'reorder_sub': 'Arrange pages',
      'compress_title': 'Compress',
      'compress_sub': 'Reduce file size',
      'repair_title': 'Repair',
      'repair_sub': 'Fix damaged PDF',
      'img_to_pdf_title': 'Image to PDF',
      'img_to_pdf_sub': 'Build from images',
      'txt_to_pdf_title': 'Text to PDF',
      'txt_to_pdf_sub': 'Convert TXT docs',
      'word_to_pdf_title': 'Word to PDF',
      'word_to_pdf_sub': 'DOCX to PDF',
      'pdf_to_img_title': 'PDF to Image',
      'pdf_to_img_sub': 'Extract photos',
      'pdf_to_txt_title': 'PDF to Text',
      'pdf_to_txt_sub': 'Extract text data',
      'pdf_to_word_title': 'PDF to Word',
      'pdf_to_word_sub': 'PDF to Editable DOCX',
      'edit_pdf_title': 'Edit PDF',
      'edit_pdf_sub': 'Modify text & images',
      'watermark_title': 'Watermark',
      'watermark_sub': 'Add brand stamp',
      'page_num_title': 'Page Number',
      'page_num_sub': 'Add numbering',
      'sign_pdf_title': 'Sign PDF',
      'sign_pdf_sub': 'Add digital signature',
      'password_title': 'Add Password',
      'password_sub': 'Secure document',
      'unlock_title': 'Unlock PDF',
      'unlock_sub': 'Remove security',
      'search_tool_hint': 'Search for a tool (e.g. Merge, Sign...)',
      'no_tools_found': 'No matching tools found.',
      'coming_soon': 'coming soon!',
      'saving': 'Saving...',
      'processing': 'Processing...',
      'select_ai_model': 'Select AI Model',
      'pro_final_model': 'Pro-Final Model',
      'scan_paper_tool': 'Scan from Paper',
      'photo_editor': 'Photo Editor',
      'drawn_sig': 'Drawn Signature',
      'scanned_sig': 'Scanned Signature',
      'imported_sig': 'Imported Signature',
      'digital_sig': 'Digital Signature',
      'id_scan_type': 'ID Scan Type',
      'place_sig_msg': 'Place your signature inside the box',
      'center_qr_msg': 'Center the QR code to scan',
      'finalize_save_id': 'Finalize & Save ID',
      'folder_content': 'Folder Content',
      'root_documents': 'Root / My Documents',
      'protected_doc': 'Protected Document',
      'protected_doc_msg':
          'This document is encrypted and requires a password to view.',
      'editable_word_doc_label': 'Editable Word Document',
      'share_to_edit_label': 'SHARE TO EDIT',
      'extracted_data_label': 'EXTRACTED DATA',
      'split_pdf_tooltip': 'Split PDF',
      'open_pdf_tooltip': 'Open Final PDF',
      'share_doc_tooltip': 'Share Document',
      'microsoft_word_label': 'Microsoft Word',
      'storage_usage_label': '{0} of {1} used',
      'docs_scanned_count': '{0} documents scanned',
      'user_label': 'User',
      'ok_btn': 'OK',
      'scanner_label': 'Scanner',
      'auto_label': 'Auto',
      'pdf_saved_library': 'PDF Saved to Library!',
      'edit_text_title': 'Edit Text',
      'sign_here_msg': 'Sign here',
      'clear_btn': 'Clear',
      'add_signature': 'Add Signature',
      'select_color': 'Select Color',
      'page_of': 'Page {0} of {1}',
      'merged_doc_prefix': 'Merged_Document',
      'split_batch_prefix': 'Split Batch',
      'optimized_doc_prefix': 'Optimized',
      'protected_doc_prefix': 'Protected',
      'confidential_label': 'CONFIDENTIAL',
      'watermarked_doc_prefix': 'Watermarked',
      'repaired_doc_prefix': 'Repaired',
      'healthcheck_error_log': 'Healthcheck: Structural corruption detected!',
      'idle': 'Idle',
      'ready': 'Ready',
      'unlocked_label': 'unlocked',
      'organized_doc_prefix': 'Organized',
      'numbered_doc_prefix': 'Numbered',
      'image_pdf_prefix': 'PDF',
      'signed_doc_prefix': 'Signed',
      'pdf_to_text': 'PDF to Text',
      'pdf_text_extractor': 'PDF Text\nExtractor',
      'pdf_to_text_desc':
          'Convert any PDF into editable text instantly.\nPerfect for data entry and repurposing content.',
      'no_text_extracted': 'No text could be extracted from this PDF.',
      'save_extracted_text': 'Save Extracted Text',
      'extraction_error': 'Extraction Error',
      'extracted_doc_prefix': 'Extracted',
      'copied_to_clipboard': 'Copied to clipboard',
      'select_from_library': 'Select from Library',
      'no_pdfs_found_library': 'No PDFs found in library',
      'pdf_library_hint':
          'Convert images or scans to PDF first to see them here.',
      'open_pdf': 'Open PDF',
      'choose_doc_source': 'Choose your\ndocument source',
      'open_pdf_hint':
          'Select a PDF from your device storage or compile one from your existing scans.',
      'phone_storage': 'Phone Storage',
      'phone_storage_hint': 'Browse PDFs in Downloads, Documents & SD Card',
      'internal_scans': 'Internal Scans',
      'internal_scans_hint': 'Open previously captured documents from this app',
      'no_scans_found': 'No scans found. Scan something first!',
      'internal_library': 'Internal Library',
      'pdf_exports': 'PDF\nExports',
      'no_pdf_exports': 'No PDF exports yet',
      'pdf_exports_hint':
          'Scan documents and export them\nto see them listed here.',
      'id_card_prefix': 'ID_CARD',
      'photo_session_label': 'Session',
      'adjust_edges': 'ADJUST EDGES',
      'enhancing': 'ENHANCING...',
      'opening_camera': 'Opening Camera...',
      'hold_steady_hint': 'Please hold steady for best accuracy',
      'rotate_label': 'Rotate',
      'pdf_text_extractor': 'PDF Text Extractor',
      'pdf_to_text_desc':
          'Extract text data from any PDF document quickly and accurately.',
      'select_pdf': 'Select PDF',
      'pick_pdf_hint': 'Choose a document from device',
      'select_file': 'Select File',
      'pick_file_hint': 'Choose any document or image',
      'select_doc_library': 'Select from Library',
      'any_to_word_desc':
          'Convert PDFs, Images, and Text files into editable Word documents (.docx)',
      'document_label': 'Document',
      'select_pdf_doc': 'Select PDF Document',
      'no_text_extracted': 'No text could be extracted from this PDF.',
      'extraction_error': 'Extraction Error',
      'extracted_doc_prefix': 'Extracted',
      'save_extracted_text': 'Save Extracted Text',
      'doc_name_label': 'Document Name',
      'filename_hint': 'Filename',
      'save_success': 'Saved Successfully!',
      'error_saving': 'Error Saving',
      'pdf_to_text': 'PDF to Text',
      'copied_to_clipboard': 'Copied to clipboard',
      'copy_label': 'Copy',
      'save_label': 'Save',
      'pdf_to_word': 'PDF to Word',
      'pdf_to_word_desc':
          'Convert your PDF documents into editable Word files (.docx)',
      'conversion_success': 'Conversion Success',
      'conversion_error_snack': 'Conversion Error: {0}',
      'share_word_doc': 'Share Word Document',
      'convert_another': 'Convert Another',
      'conversion_complete': 'Conversion Complete',
      'source_file': 'Source File',
      'pages_label': 'Pages',
      'converted_label': 'Converted',
      'converted_word_doc': 'Converted Word Document',
      'share_error_snack': 'Share Error: {0}',
      'saved_to_app_snack': 'Saved to App Scans',
      'error_saving_snack': 'Error saving: {0}',
      'save_to_library': 'Save to Library',
      'text_preview': 'Text Preview',
      'word_doc_no_preview':
          'Word document preview not available for native DOCX files.',
      'select_device': 'Select from Device',
      'select_device_sub': 'Choose a PDF from internal storage',
      'select_app': 'Select from App',
      'select_app_sub': 'Choose from your scanned documents',
      'error_preparing': 'Error preparing document: {0}',
      'error_loading_pdf': 'Error loading PDF: {0}',
      'watermark_empty': 'Watermark text cannot be empty',
      'select_wm_image': 'Please select a watermark image first',
      'saved_library_msg': 'Watermarked PDF saved to Library',
      'error_generating_wm': 'Error generating watermark: {0}',
      'stamp_doc': 'Stamp your Documents',
      'stamp_hint':
          'Add professional text or image watermarks to your PDF files instantly.',
      'select_pdf_file': 'Select PDF File',
      'text_label': 'Text',
      'image_label': 'Image',
      'watermark_text_hint': 'Watermark Text',
      'select_logo': 'Select Logo/Image',
      'change_image': 'Change Image',
      'incorrect_password': 'Incorrect password. Please try again.',
      'select_protected_scan': 'Select Protected Scan',
      'not_protected_error': 'This PDF is not password protected',
      'incorrect_password_try_again': 'Incorrect password. Please try again.',
      'unlock_failed': 'Unlock failed: {0}',
      'saved_as': 'Saved as',
      'save_failed': 'Save failed',
      'save_unlocked_pdf': 'Save Unlocked PDF',
      'save_unprotected_hint':
          'You are about to save this document without a password.',
      'save_now': 'SAVE NOW',
      'remove_protection': 'Remove Protection',
      'unlock_hint':
          'Choose a password-protected file to remove security permanently.',
      'app_gallery': 'App Gallery',
      'encrypted_doc': 'Encrypted Document',
      'unlocked_ready': 'Unlocked & Ready',
      'enter_password_to_unlock': 'Enter Password to Unlock',
      'verify_password': 'VERIFY PASSWORD',
      'save_unprotected_copy': 'SAVE UNPROTECTED COPY',
      'original': 'Original',
      'magic': 'Magic',
      'grayscale_filter': 'Grayscale',
      'bw_filter': 'B&W',
      'lighting_filter': 'Lighting',
      'rotate': 'Rotate',
      'fit_crop': 'Fit Crop',
      'manual_crop': 'Manual Crop',
      'error_prefix': 'Error',
      'doc_saved_success': 'Document saved successfully!',
      'manage_document': 'Manage Document',
      'add_page': 'Add Page',
      'no_scanned_images': 'No scanned images',
      'remove_page': 'Remove Page',
      'open_label': 'Open',
      'view_image': 'View Image',
      'error_loading_image': 'Error loading image',
    },
    'hi': {
      'rename': 'नाम बदलें',
      'export': 'निर्यात करें',
      'move': 'स्थानांतरित करें',
      'delete': 'हटाएं',
      'my_scanner': 'मेरा स्कैनर',
      'recent_captures': 'हाल के\nकैप्चर',
      'search_docs': 'दस्तावेज़ खोजें...',
      'scan_doc': 'दस्तावेज़ स्कैन करें',
      'settings': 'सेटिंग्स',
      'tools_hub': 'टूल्स हब',
      'my_profile': 'मेरी प्रोफाइल',
      'dark_mode': 'डार्क मोड',
      'language': 'भाषा',
      'app_lock': 'ऐप लॉक',
      'pdf_quality': 'PDF गुणवत्ता',
      'version': 'संस्करण',
      'privacy_policy': 'गोपनीयता नीति',
      'preferences': 'वरीयताएँ',
      'security': 'सुरक्षा',
      'exports': 'निर्यात',
      'about': 'बारे में',
      'my_documents': 'मेरे दस्तावेज़',
      'recent_scans': 'हाल के स्कैन',
      'recycle_bin': 'रद्दी टोकरी',
      'logout': 'लॉग आउट',
      'login': 'लॉग इन',
      'documents': 'दस्तावेज़',
      'tools': 'टूल्स',
      'profile': 'प्रोफाइल',
      'selected': 'चयनित',
      'unlock_biometrics': 'बायोमेट्रिक्स से अनलॉक करें',
      'exit_app': 'ऐप से बाहर निकलें',
      'scanner_locked': 'डॉक्यूमेंट स्कैनर लॉक है',
      'auth_required': 'फाइलों तक पहुंचने के लिए प्रमाणीकरण आवश्यक है',
      'guest_user': 'अतिथि उपयोगकर्ता',
      'sign_in_to_sync': 'अपने स्कैन सिंक करने के लिए साइन इन करें',
      'login_signup': 'साइन इन / रजिस्टर',
      'new_folder': 'नया फोल्डर',
      'folder_name': 'फोल्डर का नाम',
      'delete_folder': 'फोल्डर हटाएं?',
      'delete_folder_msg': 'अंदर की चीजें मुख्य लाइब्रेरी में ले जाई जाएंगी।',
      'pages_files_count': '{0} पेज • {1} फाइलें',
      'select_source': 'स्रोत चुनें',
      'choose_scanned_docs': 'अपने स्कैन किए गए दस्तावेज़ों में से चुनें',
      'pick_pdf_storage': 'अपने डिवाइस स्टोरेज से पीडीएफ चुनें',
      'no_pdf_error': 'चुने गए दस्तावेज़ में अभी तक पीडीएफ नहीं है।',
      'page_numbering': 'पेज नंबरिंग',
      'add_page_numbers': 'पेज नंबर जोड़ें',
      'page_numbering_hint':
          'अनुकूलन योग्य पेज नंबर जोड़ने के लिए\nएक पीडीएफ दस्तावेज़ चुनें।',
      'numbered_pdf_saved': 'नंबर वाला पीडीएफ सफलतापूर्वक सहेजा गया!',
      'cover_page_no_number': 'कवर पेज — कोई नंबर नहीं',
      'skip_cover': 'कवर छोड़ें',
      'format_label': 'प्रारूप',
      'position_label': 'स्थिति',
      'color_label': 'रंग',
      'size_label': 'आकार',
      'apply_label': 'लागू करें',
      'top_left': 'ऊपर बाईं ओर',
      'top_center': 'ऊपर मध्य',
      'top_right': 'ऊपर दाईं ओर',
      'bottom_left': 'नीचे बाईं ओर',
      'bottom_center': 'नीचे मध्य',
      'bottom_right': 'नीचे दाईं ओर',
      'repair_pdf': 'पीडीएफ रिपेयर',
      'repair_hint':
          'हमारे अति-सटीक साल्वेज इंजन के साथ दूषित या अपठनीय दस्तावेजों को ठीक करें।',
      'drop_corrupted_pdf': 'दूषित पीडीएफ डालें',
      'repair_sub_hint':
          'टूटी हुई संरचनाओं को ठीक करें और पेजों को पुनर्प्राप्त करें',
      'select_file_label': 'फाइल चुनें',
      'healthy_status': 'स्वस्थ',
      'corrupted_status': 'दूषित',
      'verified_integrity': 'सत्यापित अखंडता',
      'structural_instability': 'संरचनात्मक अस्थिरता',
      'salvage_logs': 'साल्वेज लॉग्स',
      'engine_standby': 'इंजन स्टैंडबाय',
      'salvaging_doc': 'दस्तावेज़ साल्वेजिंग...',
      'repair_doc_label': 'दस्तावेज़ रिपेयर करें',
      'repair_successful': 'रिपेयर सफल',
      'repair_success_hint':
          'आंतरिक संरचनाओं को स्थिर किया गया और दृश्य संदर्भ को बचाया गया।',
      'save_view_pdf': 'सहेजें और पीडीएफ देखें',
      'repair_another': 'दूसरी फाइल रिपेयर करें',
      'selected_label': 'चयनित: {0}',
      'path_label': 'पथ: {0}',
      'size_label_kb': 'आकार: {0} KB',
      'empty_file_error': 'त्रुटि: चयनित फाइल खाली है (0 बाइट्स)।',
      'empty_file_snack': 'चयनित फाइल खाली है और इसे ठीक नहीं किया जा सकता है।',
      'healthcheck_error': 'हेल्थचेक: संरचनात्मक भ्रष्टाचार का पता चला!',
      'no_pdf_version_error':
          'त्रुटि: चयनित दस्तावेज़ में कोई पीडीएफ संस्करण नहीं है।',
      'file_not_found_error': 'त्रुटि: {0} पर फाइल नहीं मिली',
      'library_file_empty_error': 'त्रुटि: लाइब्रेरी में स्रोत फाइल खाली है।',
      'library_file_empty_snack':
          'लाइब्रेरी फाइल खाली है और इसे ठीक नहीं किया जा सकता है।',
      'starting_repair_engine': 'उन्नत रिपेयर इंजन v2.0 शुरू किया जा रहा है',
      'initializing_analysis': 'विश्लेषण शुरू किया जा रहा है',
      'stabilizing_bytes': 'बाइट्स को स्थिर किया जा रहा है',
      'reconstructing_structure': 'संरचना का पुनर्निर्माण किया जा रहा है',
      'byte_stream_norm':
          'स्टेज 0 लागू किया जा रहा है: बाइट-स्ट्रीम सामान्यीकरण...',
      'structural_repair': 'स्टेज 1 लागू किया जा रहा है: संरचनात्मक रिपेयर...',
      'repair_success_log': 'सर्जिकल रिपेयर सफल। अखंडता बहाल की गई।',
      'fatal_recovery_error': 'घातक रिकवरी त्रुटि: {0}',
      'structure_too_far_gone':
          'दस्तावेज़ की संरचना स्वचालित साल्वेज के लिए बहुत अधिक खराब हो चुकी है।',
      'repair_failed_snack': 'रिपेयर विफल: {0}',
      'save_success_snack': 'सफलता! पीडीएफ लाइब्रेरी और डाउनलोड में सहेजा गया।',
      'save_failed_log': 'सहेजने में विफल: {0}',
      'pdf_to_image': 'PDF से फोटो',
      'init_conversion': 'रूपांतरण शुरू किया जा रहा है...',
      'extracted_page': 'निकाला गया पेज {0}',
      'images_from_label': '{0} से फोटो',
      'extracted_images_count_log': 'PDF से {0} फोटो निकाले गए।',
      'extract_success_snack':
          'सफलतापूर्वक {0} फोटो निकाले गए! होम में सहेजा गया।',
      'extract_error_snack': 'निकालने में त्रुटि: {0}',
      'extract_photos_hint':
          'पेजों को उच्च-गुणवत्ता वाले फोटो के रूप में निकालें',
      'extract_as_images': 'फोटो के रूप में निकालें',
      'extraction_quality': 'निकालने की गुणवत्ता',
      'standard_label': 'स्टैंडर्ड',
      'hd_label': 'HD',
      'ultra_label': 'अल्ट्रा',
      'fast_conversion': 'तेज़ रूपांतरण',
      'great_balance': 'शानदार संतुलन',
      'print_ready': 'प्रिंट के लिए तैयार',
      'pdf_to_word': 'PDF से वर्ड',
      'converting_pdf_to_word': 'PDF को वर्ड में बदला जा रहा है...',
      'extracting_text_doc':
          'टेक्स्ट निकाला जा रहा है और दस्तावेज़ बनाया जा रहा है',
      'conversion_success': 'रूपांतरण सफल!',
      'conversion_error_snack': 'रूपांतरण त्रुटि: {0}',
      'share_error_snack': 'शेयर त्रुटि: {0}',
      'saved_as': 'के रूप में सहेजा गया',
      'save_failed': 'सहेजना विफल रहा',
      'save_unlocked_pdf': 'अनलॉक किया गया पीडीएफ सहेजें',
      'save_unprotected_hint':
          'आप इस दस्तावेज़ को बिना पासवर्ड के सहेजने वाले हैं।',
      'save_now': 'अभी सहेजें',
      'remove_protection': 'सुरक्षा हटाएं',
      'unlock_hint':
          'स्थायी रूप से सुरक्षा हटाने के लिए पासवर्ड-सुरक्षित फ़ाइल चुनें।',
      'app_gallery': 'ऐप गैलरी',
      'encrypted_doc': 'एन्क्रिप्टेड दस्तावेज़',
      'unlocked_ready': 'अनलॉक और तैयार',
      'enter_password_to_unlock': 'अनलॉक करने के लिए पासवर्ड दर्ज करें',
      'verify_password': 'पासवर्ड सत्यापित करें',
      'save_unprotected_copy': 'असुरक्षित प्रति सहेजें',
      'from_device': 'डिवाइस से',
      'save_to_library_success': 'लाइब्रेरी में सहेजा गया!',
      'save_error_snack_param': 'सहेजने में त्रुटि: {0}',
      'choose_source': 'स्रोत चुनें',
      'pick_from_device': 'डिवाइस से चुनें',
      'browse_local_files': 'अपनी लोकल फाइलें ब्राउज़ करें',
      'from_library_sub_hint': 'एक सहेजा गया दस्तावेज़ चुनें',
      'convert_to_editable_word': 'संपादन योग्य वर्ड में बदलें',
      'convert_word_hint':
          'टेक्स्ट सामग्री को सुरक्षित रखते हुए किसी भी PDF को (.docx) फाइल में बदलें।',
      'conversion_complete': 'रूपांतरण पूरा हुआ!',
      'convert_another': 'दूसरा बदलें',
      'share_docx': 'DOCX शेयर करें',
      'save_to_library_btn': 'लाइब्रेरी में सहेजें',
      'converted_word_doc': 'परिवर्तित वर्ड दस्तावेज़',
      'converted_label': 'परिवर्तित',
      'text_to_pdf': 'टेक्स्ट से PDF',
      'enter_text_snack': 'कृपया बदलने के लिए कुछ टेक्स्ट दर्ज करें',
      'text_doc_default_name': 'टेक्स्ट दस्तावेज़ {0}_{1}_{2}',
      'save_pdf_doc_title': 'PDF दस्तावेज़ सहेजें',
      'assign_name_hint': 'अपने टेक्स्ट दस्तावेज़ के लिए एक नाम निर्दिष्ट करें',
      'name_label': 'नाम',
      'cancel_label': 'रद्द करें',
      'generate_save_btn': 'बनाएं और सहेजें',
      'converted_text_title': 'परिवर्तित टेक्स्ट',
      'text_imported_snack': 'स्कैन से टेक्स्ट आयात किया गया',
      'clear_text_title': 'टेक्स्ट साफ करें?',
      'clear_text_hint': 'यह संपादक से सभी टेक्स्ट को हटा देगा।',
      'clear_label': 'साफ करें',
      'clear_all_tooltip': 'सभी टेक्स्ट साफ करें',
      'scan_text_tooltip': 'कैमरे से टेक्स्ट स्कैन करें',
      'type_paste_hint':
          'यहाँ टाइप करना शुरू करें या अपनी सामग्री पेस्ट करें...',
      'converting_label': 'बदला जा रहा है...',
      'convert_to_pdf_btn': 'PDF में बदलें',
      'word_to_pdf': 'वर्ड से PDF',
      'word_doc_default_name': 'वर्ड_दस्तावेज़_{0}_{1}_{2}',
      'assign_converted_name_hint':
          'अपने परिवर्तित दस्तावेज़ के लिए एक नाम निर्दिष्ट करें',
      'convert_save_btn': 'बदलें और सहेजें',
      'converted_from_word_log': 'वर्ड से परिवर्तित: {0}',
      'select_word_doc': 'वर्ड दस्तावेज़ चुनें',
      'tap_to_change_file': 'फाइल बदलने के लिए टैप करें',
      'supported_format_docx': 'समर्थित प्रारूप: .docx',
      'id_card_scanner': 'आईडी कार्ड स्कैनर',
      'choose_scan_type': 'स्कैन का प्रकार चुनें',
      'select_scan_method_hint':
          'चुनें कि आप अपना आईडी कार्ड कैसे स्कैन करना चाहते हैं',
      'single_side': 'एक तरफ',
      'single_side_hint': 'केवल आईडी कार्ड के सामने के हिस्से को स्कैन करें',
      'double_side': 'दोनों तरफ',
      'double_side_hint':
          'सामने और पीछे दोनों हिस्सों को सही ढंग से कैप्चर करें',
      'front_side_editor': 'सामने का हिस्सा संपादक',
      'back_side_editor': 'पीछे का हिस्सा संपादक',
      'capture_front_snack': 'पहले सामने का हिस्सा कैप्चर करें!',
      'capture_back_snack': 'पहले पीछे का हिस्सा कैप्चर करें!',
      'id_card_save_success': 'आईडी कार्ड सफलतापूर्वक सहेजा गया!',
      'both_sides_scan': 'दोनों तरफ का स्कैन',
      'single_side_scan': 'एक तरफ का स्कैन',
      'front_side': 'सामने का हिस्सा',
      'back_side': 'पीछे का हिस्सा',
      'tap_to_capture': 'कैप्चर करने के लिए टैप करें',
      'finalize_save': 'अंतिम रूप दें और सहेजें',
      'ocr_result': 'OCR परिणाम',
      'text_copied_snack': 'टेक्स्ट क्लिपबोर्ड पर कॉपी किया गया',
      'recognized_text_hint': 'पहचाना गया टेक्स्ट यहाँ दिखाई देगा...',
      'copy_label': 'कॉपी',
      'share_label': 'साझा करें',
      'save_label': 'सहेजें',
      'save_ocr_result_title': 'OCR परिणाम सहेजें',
      'doc_name_label': 'दस्तावेज़ का नाम',
      'saved_to_docs_snack': 'आपके दस्तावेज़ों में सहेजा गया!',
      'document_pages': 'दस्तावेज़ पृष्ठ',
      'ocr_error_prefix': 'OCR त्रुटि: {0}',
      'page_prefix': 'पृष्ठ',
      'add_page_btn': 'पृष्ठ जोड़ें',
      'extract_text_btn': 'टेक्स्ट निकालें',
      'add_custom_size': 'कस्टम आकार जोड़ें',
      'label_hint': 'लेबल (जैसे मेरा वीज़ा)',
      'width_label': 'चौड़ाई',
      'height_label': 'ऊंचाई',
      'cancel_btn': 'रद्द करें',
      'add_btn': 'जोड़ें',
      'select_id_photo_size': 'आईडी फोटो आकार चुनें',
      'custom_size_card': 'कस्टम आकार',
      'photo_size_passport': 'पासपोर्ट',
      'photo_size_visa_us': 'वीज़ा (US)',
      'photo_size_id_card': 'आईडी कार्ड',
      'photo_size_pan_card': 'पैन कार्ड',
      'photo_size_driving_license': 'ड्राइविंग लाइसेंस',
      'session_organizer': 'सत्र आयोजक',
      'capture_more': 'और कैप्चर करें',
      'save_exit': 'सहेजें और बाहर निकलें',
      'photos_saved_home': 'ID फोटो होम स्क्रीन पर सहेजे गए!',
      'scan_result': 'स्कैन परिणाम',
      'open_link': 'लिंक खोलें',
      'call_label': 'कॉल करें',
      'send_email': 'ईमेल भेजें',
      'could_not_open_link': 'लिंक नहीं खुल सका',
      'open_in_browser': 'ब्राउज़र में खोलें',
      'search_web': 'वेब पर खोजें',
      'sig_min_one_snack':
          'कृपया कम से कम एक हस्ताक्षर कैप्चर करें या ड्रा करें।',
      'sig_pack_saved_snack': 'हस्ताक्षर पैक सहेजा गया!',
      'tap_to_edit': 'संपादित करने के लिए टैप करें',
      'scan_more': 'और स्कैन करें',
      'draw_new': 'नया ड्रा करें',
      'save_sig_pack': 'हस्ताक्षर पैक सहेजें',
      'scan_history': 'स्कैन इतिहास',
      'clear_all': 'सभी साफ़ करें',
      'clear_history_dialog': 'इतिहास साफ़ करें',
      'clear_history_confirm': 'क्या आप वाकई सभी स्कैन इतिहास हटाना चाहते हैं?',
      'no_scan_history': 'अभी तक कोई स्कैन इतिहास नहीं है',
      'no_scan_history_sub':
          'आपके स्कैन किए गए क्यूआर और बारकोड यहां दिखाई देंगे।',
      'doc_signed_saved_snack': 'दस्तावेज़ हस्ताक्षरित और सहेजा गया!',
      'save_doc_as': 'दस्तावेज़ को इस रूप में सहेजें',
      'enter_signed_pdf_name':
          'अपने हस्ताक्षरित पीडीएफ के लिए एक नाम दर्ज करें:',
      'filename_hint': 'फ़ाइल का नाम',
      'enter_text': 'टेक्स्ट दर्ज करें',
      'my_signatures': 'मेरे हस्ताक्षर',
      'no_saved_signatures': 'अभी तक कोई सहेजा गया हस्ताक्षर नहीं है।',
      'sign_document': 'दस्तावेज़ पर हस्ताक्षर करें',
      'done_btn': 'हो गया',
      'sign_label': 'हस्ताक्षर',
      'text_label': 'टेक्स्ट',
      'date_label': 'दिनांक',
      'prev_label': 'पिछला',
      'next_label': 'अगला',
      'manual_crop': 'मैनुअल क्रॉप',
      'crop_to_size': '{0} पर क्रॉप करें',
      'size_crop': 'साइज क्रॉप',
      'grayscale_label': 'ग्रेस्केल',
      'id_specialized_cat': 'आईडी और विशेष',
      'id_card_title': 'आईडी कार्ड स्कैनर',
      'id_card_sub': 'अपने आईडी कार्ड को स्कैन और डिजिटल करें',
      'id_photo_title': 'आईडी फोटो मेकर',
      'id_photo_sub': 'पासपोर्ट आकार के फोटो बनाएं',
      'signature_tool_title': 'डिजिटल हस्ताक्षर',
      'signature_tool_sub': 'अपना हस्ताक्षर बनाएं और सहेजें',
      'qr_tool_title': 'QR और बारकोड',
      'qr_tool_sub': 'QR कोड स्कैन करें या बनाएं',
      'ai_smart_cat': 'AI और स्मार्ट टूल्स',
      'ocr_title': 'OCR (टेक्स्ट निकालें)',
      'ocr_sub': 'छवियों से तुरंत टेक्स्ट निकालें',
      'ai_chat_title': 'AI दस्तावेज़ चैट',
      'ai_chat_sub': 'अपने दस्तावेज़ों के साथ चैट करें',
      'rename_doc': 'दस्तावेज़ का नाम बदलें',
      'enter_new_name': 'नया नाम दर्ज करें',
      'save_to_device': 'डिवाइस में PDF सेव करें',
      'move_to_folder': 'फ़ोल्डर में ले जाएं',
      'back_to_library': 'लाइब्रेरी पर वापस जाएं',
      'library_empty': 'आपकी लाइब्रेरी खाली है',
      'start_scanning': 'अपना संग्रह बनाने के लिए स्कैनिंग शुरू करें',
      'no_results': 'कोई परिणाम नहीं मिला',
      'try_different_term': 'एक अलग खोज शब्द आज़माएं',
      'change_name': 'नाम बदलें',
      'choose_profile_pic': 'प्रोफ़ाइल फ़ोटो चुनें',
      'remove_profile_pic': 'प्रोफ़ाइल फ़ोटो हटाएँ',
      'profile_pic_updated': 'प्रोफ़ाइल फ़ोटो अपडेट की गई!',
      'failed_pick_image': 'फ़ोटो चुनने में विफल',
      'storage': 'स्टोरेज',
      'scanning_history': 'स्कैनिंग इतिहास',
      'help_support': 'सहायता और समर्थन',
      'login_subtitle': 'अपने खाते में साइन इन करें',
      'login_success': 'लॉगिन सफल!',
      'storage_usage': 'स्टोरेज का उपयोग',
      'local_storage': 'लोकल स्टोरेज',
      'cloud_storage': 'क्लाउड स्टोरेज',
      'not_configured': 'सेट नहीं किया गया',
      'space_left_msg': 'आपके पास नए स्कैन के लिए पर्याप्त जगह है!',
      'contact_us_msg':
          'डॉक स्कैनर के साथ समस्या आ रही है?\nनकृपया हमसे devopsaksentt@gmail.com पर संपर्क करें',
      'not_logged_in': 'लॉग इन नहीं है',
      'signin_register': 'साइन इन / रजिस्टर',
      'profile_name_updated': 'प्रोफ़ाइल नाम अपडेट किया गया!',
      'edit_profile_name': 'प्रोफ़ाइल नाम बदलें',
      'enter_your_name': 'अपना नाम दर्ज करें',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'create': 'बनाएं',
      'organize_pdf': 'PDF व्यवस्थित करें',
      'optimize_pdf': 'PDF अनुकूलित करें',
      'convert_pdf': 'PDF बदलें',
      'edit_pdf_cat': 'PDF संपादित करें',
      'security_cat': 'सुरक्षा',
      'merge_title': 'मर्ज करें',
      'merge_sub': 'PDF को एक साथ जोड़ें',
      'split_title': 'विभाजित करें',
      'split_sub': 'पेज अलग करें',
      'reorder_title': 'क्रम बदलें',
      'reorder_sub': 'पेज व्यवस्थित करें',
      'compress_title': 'कंप्रेस करें',
      'compress_sub': 'फाइल का आकार कम करें',
      'repair_title': 'रिपेयर करें',
      'repair_sub': 'क्षतिग्रस्त PDF ठीक करें',
      'img_to_pdf_title': 'फोटो से PDF',
      'img_to_pdf_sub': 'फोटो से फाइल बनाएं',
      'txt_to_pdf_title': 'टेक्स्ट से PDF',
      'txt_to_pdf_sub': 'TXT फाइल बदलें',
      'word_to_pdf_title': 'Word से PDF',
      'word_to_pdf_sub': 'DOCX से PDF',
      'pdf_to_img_title': 'PDF से फोटो',
      'pdf_to_img_sub': 'फोटो निकालें',
      'pdf_to_txt_title': 'PDF से टेक्स्ट',
      'pdf_to_txt_sub': 'टेक्स्ट डेटा निकालें',
      'pdf_to_word_title': 'PDF से Word',
      'pdf_to_word_sub': 'PDF से DOCX फाइल',
      'edit_pdf_title': 'PDF संपादित करें',
      'edit_pdf_sub': 'टेक्स्ट और फोटो बदलें',
      'watermark_title': 'वाटरमार्क',
      'watermark_sub': 'अपना लोगो जोड़ें',
      'page_num_title': 'पेज नंबर',
      'page_num_sub': 'नंबर डालें',
      'sign_pdf_title': 'PDF साइन करें',
      'sign_pdf_sub': 'डिजिटल सिग्नेचर जोड़ें',
      'password_title': 'पासवर्ड डालें',
      'password_sub': 'फाइल सुरक्षित करें',
      'unlock_title': 'PDF अनलॉक करें',
      'unlock_sub': 'पासवर्ड हटाएं',
      'search_tool_hint': 'टूल खोजें (जैसे मर्ज, साइन...)',
      'no_tools_found': 'कोई टूल नहीं मिला।',
      'coming_soon': 'जल्द ही आ रहा है!',
      'from_device': 'डिवाइस से',
      'from_device_sub': 'स्टोरेज से PDF चुनें',
      'from_library': 'लाइब्रेरी से',
      'from_library_sub': 'स्कैन किए गए दस्तावेजों से चुनें',
      'saving': 'सहेज रहा है...',
      'processing': 'प्रोसेसिंग...',
      'select_ai_model': 'AI मॉडल चुनें',
      'pro_final_model': 'प्रो-फाइनल मॉडल',
      'scan_paper_tool': 'कागज से स्कैन करें',
      'photo_editor': 'फोटो एडिटर',
      'drawn_sig': 'ड्रॉ किया हुआ सिग्नेचर',
      'scanned_sig': 'स्कैन किया हुआ सिग्नेचर',
      'imported_sig': 'इंपोर्ट किया हुआ सिग्नेचर',
      'digital_sig': 'डिजिटल सिग्नेचर',
      'id_scan_type': 'ID स्कैन का प्रकार',
      'single_side': 'एक तरफ',
      'double_side': 'दोनों तरफ',
      'place_sig_msg': 'बॉक्स के अंदर सिग्नेचर करें',
      'center_qr_msg': 'स्कैन करने के लिए QR कोड को बीच में रखें',
      'finalize_save_id': 'ID को सहेजें और सुरक्षित करें',
      'error_prep_doc': 'दस्तावेज़ तैयार करने में त्रुटि',
      'edit_label': 'संपादित करें',
      'original': 'ओरिजनल',
      'magic': 'मैजिक',
      'grayscale_filter': 'ग्रेस्केल',
      'bw_filter': 'ब्लैक एंड व्हाइट',
      'lighting_filter': 'लाइटिंग',
      'passport': 'पासपोर्ट',
      'visa_us': 'वीजा (US)',
      'id_card_size': 'आईडी कार्ड',
      'pan_card': 'पैन कार्ड',
      'front_label': 'सामने',
      'back_label': 'पीछे',
      'image_to_pdf': 'छवि से पीडीएफ',
      'compress_pdf': 'पीडीएफ कंप्रेस करें',
      'compress_pdf_title': 'पीडीएफ आकार कम करें',
      'compress_hint':
          'विजुअल गुणवत्ता बनाए रखते हुए पीडीएफ फाइल का आकार छोटा करें।',
      'from_device_label': 'डिवाइस से',
      'from_library_label': 'लाइब्रेरी से',
      'no_pdfs_library': 'लाइब्रेरी में कोई पीडीएफ नहीं है!',
      'already_optimized': 'यह फाइल पहले से ही काफी अनुकूलित है!',
      'pdf_saved_msg': 'पीडीएफ सहेजा गया!',
      'compression_level': 'कंप्रेशन लेवल',
      'recommended_level': 'अनुशंसित',
      'recommended_desc': 'आकार और गुणवत्ता के बीच सबसे अच्छा संतुलन',
      'extreme_level': 'एक्सट्रीम',
      'extreme_desc': 'अधिकतम कटौती (छवियों को फिर से सैंपल किया जाएगा)',
      'basic_level': 'बेसिक',
      'basic_desc': 'न्यूनतम कटौती, मूल डेटा सुरक्षित रखता है',
      'saved_percent_msg': '{0}% बचत',
      'already_optimized_title': 'पहले से अनुकूलित',
      'pdf_now_size': 'आपका पीडीएफ अब {0} MB का है',
      'min_size_msg': 'फाइल पहले से ही अपने न्यूनतम आकार में है।',
      'before_label': 'पहले',
      'after_label': 'बाद में',
      'save_optimized_pdf': 'अनुकूलित पीडीएफ सहेजें',
      'save_anyway': 'वैसे ही सहेजें',
      'split_pdf': 'पीडीएफ विभाजित करें',
      'select_device': 'डिवाइस से चुनें',
      'select_device_sub': 'अपनी लोकल पीडीएफ फाइलें ब्राउज़ करें',
      'select_app': 'ऐप से चुनें',
      'select_app_sub': 'अपने स्कैन किए गए दस्तावेज़ों में से चुनें',
      'select_library': 'लाइब्रेरी से चुनें',
      'no_pdfs_found': 'अभी तक आपकी लाइब्रेरी में कोई पीडीएफ नहीं मिला!',
      'change_label': 'बदलें',
      'by_range': 'रेंज के अनुसार',
      'extract_all': 'सभी निकालें',
      'page_ranges': 'पेज रेंज',
      'add_new_range': 'नई रेंज जोड़ें',
      'from_label': 'से',
      'to_label': 'तक',
      'zip_hint':
          'हर पेज एक अलग पीडीएफ बन जाएगा। हम उन्हें आपके लिए एक ज़िप (ZIP) में बंडल कर देंगे।',
      'extract_all_zip': 'सभी निकालें और ज़िप करें',
      'split_successful': 'विभाजन सफल! लाइब्रेरी में सहेजा गया।',
      'extracted_multiple': 'कई फाइलें निकाली गईं! ज़िप डाउनलोड में सहेजा गया।',
      'repaired_doc_prefix': 'रिपेयर्ड',
      'repaired_document': 'रिपेयर्ड दस्तावेज',
      'organized_doc_prefix': 'ऑर्गेनाइज्ड',
      'pdf_locked_error':
          'पीडीएफ पासवर्ड से सुरक्षित है और इसे व्यवस्थित नहीं किया जा सकता है।',
      'add_images': 'छवियां जोड़ें',
      'gallery_label': 'गैलरी',
      'pick_from_library': 'लाइब्रेरी से चुनें',
      'library_empty_msg': 'लाइब्रेरी खाली है!',
      'edit_page': 'पेज संपादित करें',
      'convert_label': 'बदलें',
      'pdf_gen_success': 'पीडीएफ सफलतापूर्वक तैयार किया गया!',
      'page_size': 'पेज का आकार:',
      'no_images_selected': 'कोई छवि नहीं चुनी गई',
      'add_from_gallery': 'गैलरी से जोड़ें',
      'add_from_camera': 'कैमरे से जोड़ें',
      'add_from_library': 'लाइब्रेरी से जोड़ें',
      'images_selected_count': '{0} छवियां चुनी गईं',
      'generate_pdf': 'पीडीएफ तैयार करें',
      'protect_pdf': 'पीडीएफ सुरक्षित करें',
      'lock_document': 'अपना दस्तावेज़ लॉक करें',
      'encryption_hint':
          'हम आपके डेटा को निजी और सुरक्षित रखने के लिए एईएस 256-बिट एन्क्रिप्शन का उपयोग करते हैं।',
      'file_locked': 'फ़ाइल लॉक है',
      'file_protected_msg':
          'यह दस्तावेज़ पहले से ही सुरक्षित है। इसे संशोधित करने के लिए वर्तमान पासवर्ड दर्ज करें।',
      'unlock_label': 'अनलॉक',
      'save_protected_pdf': 'सुरक्षित पीडीएफ सहेजें',
      'protected_name_hint': 'अपने सुरक्षित दस्तावेज़ को एक नाम दें:',
      'save_securely': 'सुरक्षित रूप से सहेजें',
      'select_pdf_error': 'कृपया पहले एक पीडीएफ फाइल चुनें',
      'enter_password_error': 'कृपया पासवर्ड दर्ज करें',
      'passwords_mismatch': 'पासवर्ड मेल नहीं खाते',
      'pdf_protected_success':
          'पीडीएफ सुरक्षित किया गया और {0} के रूप में सहेजा गया',
      'set_password': 'पासवर्ड सेट करें',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'strength_label': 'शक्ति: {0}',
      'min_chars_hint': 'न्यूनतम 6 अक्षर',
      'protect_pdf_now': 'अब पीडीएफ सुरक्षित करें',
      'weak_label': 'कमजोर',
      'medium_label': 'औसत',
      'strong_label': 'मजबूत',
      'strength_none': 'कोई नहीं',
      'unlock_pdf': 'पीडीएफ अनलॉक करें',
      'not_protected_error': 'यह फ़ाइल पासवर्ड सुरक्षित नहीं है।',
      'pdf_unlocked_success': 'दस्तावेज़ सफलतापूर्वक अनलॉक किया गया!',
      'incorrect_password_try_again': 'गलत पासवर्ड। कृपया पुनः प्रयास करें।',
      'unlock_failed': 'अनलॉक विफल रहा: {0}',
      'save_unlocked_pdf': 'अनलॉक की गई पीडीएफ सहेजें',
      'save_unprotected_hint':
          'इस दस्तावेज़ को बिना पासवर्ड सुरक्षा के सहेजें।',
      'save_now': 'अभी सहेजें',
      'remove_protection': 'सुरक्षा हटाएं',
      'unlock_hint':
          'पासवर्ड से सुरक्षित पीडीएफ को डिक्रिप्ट करने के लिए अपलोड करें और बिना सुरक्षा के एक स्थायी प्रति सहेजें।',
      'encrypted_doc': 'एन्क्रिप्टेड दस्तावेज़',
      'unlocked_ready': 'अनलॉक और तैयार',
      'enter_password_to_unlock': 'अनलॉक करने के लिए पासवर्ड दर्ज करें',
      'verify_password': 'पासवर्ड सत्यापित करें',
      'save_unprotected_copy': 'असुरक्षित प्रति सहेजें',
      'organize_combine': 'व्यवस्थित करें और संयोजित करें',
      'pdf_composition_saved': 'पीडीएफ रचना सहेजी गई!',
      'add_pdf': 'पीडीएफ जोड़ें',
      'multi_file_organize': 'मल्टी-फ़ाइल व्यवस्थित करें',
      'organize_hint':
          'उन्हें व्यवस्थित करने और संयोजित करने के लिए एक या अधिक पीडीएफ जोड़ें।',
      'drag_interleave_hint':
          'विभिन्न फाइलों से पेजों को बीच में लाने के लिए ड्रैग करें।',
      'pick_pdf_storage': 'अपने डिवाइस स्टोरेज से पीडीएफ चुनें',
      'no_pdf_error': 'चुने गए दस्तावेज़ में अभी तक PDF नहीं है।',
      'compress_pdf': 'PDF कंप्रेस करें',
      'compress_pdf_title': 'PDF का साइज़ कम करें',
      'compress_hint':
          'विज़ुअल क्वालिटी बनाए रखते हुए PDF फ़ाइल का साइज़ कम करें।',
      'from_device_label': 'डिवाइस से',
      'from_library_label': 'ऐप लाइब्रेरी से',
      'no_pdfs_library': 'लाइब्रेरी में कोई PDF नहीं है!',
      'already_optimized': 'यह फ़ाइल पहले से ही अत्यधिक अनुकूलित है!',
      'pdf_saved_msg': 'PDF सहेजा गया!',
      'compression_level': 'कंप्रेशन लेवल',
      'recommended_level': 'अनुशंसित',
      'recommended_desc': 'साइज़ और क्वालिटी के बीच सबसे अच्छा संतुलन',
      'extreme_level': 'अत्यधिक',
      'extreme_desc': 'अधिकतम कमी (चित्रों को फिर से सैंपल किया जाएगा)',
      'basic_level': 'बुनियादी',
      'basic_desc': 'न्यूनतम कमी, मूल डेटा सुरक्षित रखता है',
      'saved_percent_msg': '{0}% की बचत हुई',
      'already_optimized_title': 'पहले से अनुकूलित',
      'pdf_now_size': 'आपका PDF अब {0} MB का है',
      'min_size_msg': 'फ़ाइल पहले से ही अपने न्यूनतम साइज़ पर है।',
      'before_label': 'पहले',
      'after_label': 'बाद में',
      'save_optimized_pdf': 'अनुकूलित PDF सहेजें',
      'save_anyway': 'फिर भी सहेजें',
      'split_pdf': 'PDF विभाजित करें',
      'select_device': 'डिवाइस से चुनें',
      'select_device_sub': 'अपनी स्थानीय PDF फ़ाइलें ब्राउज़ करें',
      'select_app': 'ऐप से चुनें',
      'select_app_sub': 'अपने स्कैन किए गए दस्तावेज़ों में से चुनें',
      'select_library': 'लाइब्रेरी से चुनें',
      'no_pdfs_found': 'आपकी लाइब्रेरी में अभी तक कोई PDF नहीं मिली!',
      'change_label': 'बदलें',
      'by_range': 'रेंज के अनुसार',
      'extract_all': 'सभी निकालें',
      'page_ranges': 'पेज रेंज',
      'add_new_range': 'नई रेंज जोड़ें',
      'from_label': 'से',
      'to_label': 'तक',
      'zip_hint':
          'प्रत्येक पेज एक अलग PDF बन जाएगा। हम उन्हें आपके लिए एक ZIP में बंडल करेंगे।',
      'extract_all_zip': 'सभी निकालें और ZIP करें',
      'split_successful': 'विभाजन सफल! लाइब्रेरी में सहेजा गया।',
      'extracted_multiple':
          'कई फ़ाइलें निकाली गईं! ZIP Downloads में सहेजा गया।',
      'back_label': 'पीछे',
      'add_watermark': 'वॉटरमार्क जोड़ें',
      'select_pdf_file': 'PDF फ़ाइल चुनें',
      'stamp_doc': 'अपना दस्तावेज़ स्टैम्प करें',
      'stamp_hint':
          'सभी पेजों पर टेक्स्ट या इमेज वॉटरमार्क जोड़कर अपने दस्तावेज़ों को सुरक्षित रखें।',
      'watermark_text_hint': 'वॉटरमार्क टेक्स्ट',
      'select_logo': 'लोगो इमेज चुनें',
      'change_image': 'इमेज बदलें',
      'position_label': 'स्थिति',
      'diagonal': 'तिरछा',
      'center_label': 'केंद्र',
      'top_l': 'ऊपर बाएं',
      'top_r': 'ऊपर दाएं',
      'bottom_l': 'नीचे बाएं',
      'bottom_r': 'नीचे दाएं',
      'size_label': 'साइज़',
      'scale_label': 'स्केल',
      'opacity_label': 'अपारदर्शिता',
      'text_label': 'टेक्स्ट',
      'image_label': 'इमेज',
      'watermark_empty': 'वॉटरमार्क टेक्स्ट खाली नहीं हो सकता',
      'select_wm_image': 'कृपया वॉटरमार्क इमेज चुनें',
      'saved_library_msg': 'लाइब्रेरी में सहेजा गया!',
      'error_preparing': 'दस्तावेज़ तैयार करने में त्रुटि: {0}',
      'error_loading_pdf': 'PDF लोड करने में त्रुटि: {0}',
      'error_generating_wm': 'वॉटरमार्क जेनरेट करने में त्रुटि: {0}',
      'page_organizer': 'पेज ऑर्गनाइज़र',
      'arrange_pages': 'पेज व्यवस्थित करें',
      'reorder_hint':
          'पेजों को फिर से व्यवस्थित करने के लिए दबाकर रखें और खींचें।',
      'start_adding_pages': 'पेज जोड़ना शुरू करें',
      'add_pages_hint':
          'व्यवस्थित करने के लिए कैमरा, स्कैन या फ़ाइलों से पेज जोड़ें।',
      'camera_label': 'कैमरा',
      'scans_label': 'स्कैन',
      'files_label': 'फ़ाइलें',
      'finalize_pdf': 'PDF अंतिम रूप दें',
      'finalize_hint':
          'आपके व्यवस्थित पेजों को एक नए PDF दस्तावेज़ के रूप में सहेजा जाएगा।',
      'filename_hint': 'फ़ाइल का नाम',
      'save_view': 'सहेजें और देखें',
      'saved_downloads': 'डाउनलोड में सहेजा गया',
      'saved_library': 'लाइब्रेरी में सहेजा गया',
      'error_saving': 'PDF सहेजने में त्रुटि',
      'no_scans_found': 'लाइब्रेरी में कोई स्कैन नहीं मिला',
      'add_from_scan': 'स्कैन से जोड़ें',
      'merged_doc_prefix': 'व्यवस्थित',
      'pages_count': '{0} पेज',
      'page_of': 'पेज {0} का {1}',
      'page_numbering': 'पेज नंबरिंग',
      'finalize_doc': 'दस्तावेज़ को अंतिम रूप दें',
      'draw_signature': 'हस्ताक्षर करें',
      'create_signature': 'हस्ताक्षर बनाएं',
      'scan_from_paper': 'कागज से स्कैन करें',
      'signature_weight': 'मोटाई',
      'clear_all': 'सब साफ करें',
      'add_to_session': 'सत्र में जोड़ें',
      'save_signature': 'हस्ताक्षर सहेजें',
      'draw_first_msg': 'कृपया पहले हस्ताक्षर करें!',
      'sig_saved_msg': 'हस्ताक्षर सहेजा गया!',
      'scan_err_msg': 'स्कैन त्रुटि',
      'pdf_editor': 'पीडीएफ संपादक',
      'annotate': 'एनोटेट',
      'shapes': 'आकृतियाँ',
      'insert': 'सम्मिलित करें',
      'hand_tool': 'हाथ',
      'pen_tool': 'पेन',
      'marker_tool': 'मार्कर',
      'eraser_tool': 'इरेज़र',
      'text_tool': 'टेक्स्ट',
      'rectangle': 'आयत',
      'circle': 'वृत्त',
      'arrow': 'तीर',
      'line': 'रेखा',
      'save_changes': 'परिवर्तन सहेजें',
      'discard_changes': 'परिवर्तन छोड़ें',
      'unsaved_changes_msg': 'आपके पास न सहेजे गए परिवर्तन हैं। छोड़ें?',
      'edit_pdf': 'पीडीएफ संपादित करें',
      'pro_editor': 'प्रोफेशनल पीडीएफ संपादक',
      'pro_editor_hint':
          'सटीक उपकरणों के साथ अपने दस्तावेज़ों को ड्रा करें, टेक्स्ट, आकृतियाँ जोड़ें या हस्ताक्षर करें।',
      'select_pdf_to_edit': 'संपादित करने के लिए पीडीएफ चुनें',
      'highlight_tool': 'हाइलाइट',
      'rect_label': 'आयत',
      'circle_label': 'वृत्त',
      'line_label': 'रेखा',
      'arrow_label': 'तीर',
      'date_label': 'तारीख',
      'checkmark_label': 'चेकमार्क',
      'signature_label': 'हस्ताक्षर',
      'editing_selected': 'चयनित तत्व का संपादन',
      'size_upper': 'आकार',
      'opacity_upper': 'अपारदर्शिता',
      'select_document': 'दस्तावेज़ चुनें',
      'app_library': 'ऐप लाइब्रेरी',
      'library_hint': 'अपने स्कैन किए गए दस्तावेज़ों में से चुनें',
      'files_storage': 'फ़ाइलें / संग्रहण',
      'storage_hint': 'अपने डिवाइस स्टोरेज से एक पीडीएफ चुनें',
      'save_document': 'दस्तावेज़ सहेजें',
      'document_name': 'दस्तावेज़ का नाम',
      'edited_prefix': 'संपादित',
      'edited_doc_default': 'संपादित दस्तावेज़',
      'saved_downloads': 'Downloads/DocumentScanner में सहेजा गया!',
      'saved_library': 'लाइब्रेरी और फ़ाइलों में सहेजा गया!',
      'error_saving': 'दस्तावेज़ सहेजने में त्रुटि।',
      'camera_label': 'कैमरा',
      'scans_label': 'स्कैन',
      'files_label': 'फ़ाइलें',
      'storage_usage_label': '{1} में से {0} उपयोग किया गया',
      'docs_scanned_count': '{0} दस्तावेज़ स्कैन किए गए',
      'close': 'बंद करें',
      'fit_crop': 'फिट क्रॉप',
      'manual_crop': 'मैनुअल',
      'data_management': 'डेटा प्रबंधन',
      'optimize_library': 'लाइब्रेरी अनुकूलित करें',
      'reclaim_storage_sub': 'स्टोरेज खाली करें और ऐप तेज़ करें',
      'app_lock_sub': 'खोलने के लिए बायोमेट्रिक या पिन आवश्यक है',
      'no_security_msg': 'इस डिवाइस पर कोई सुरक्षा सेट नहीं है',
      'enabled': 'चालू',
      'disabled': 'बंद',
      'sys_default': 'सिस्टम डिफॉल्ट',
      'always_light': 'हमेशा लाइट',
      'always_dark': 'हमेशा डार्क',
      'low_qual': 'कम (तेज़ / छोटा)',
      'med_qual': 'मध्यम',
      'high_qual': 'उच्च (सबसे अच्छा)',
      'optimizing_library_msg': 'लाइब्रेरी अनुकूलित हो रही है...',
      'do_not_close_app': 'कृपया ऐप बंद न करें',
      'opt_success': 'लाइब्रेरी सफलतापूर्वक अनुकूलित हो गई!',
      'opt_failed': 'अनुकूलन विफल रहा',
      'optimize_now': 'अभी अनुकूलित करें',
      'read_terms': 'हमारी शर्तें पढ़ें',
      'manage_deleted_docs': 'हटाए गए दस्तावेज़ प्रबंधित करें',
      'opt_desc':
          'यह सभी मौजूदा स्कैन को कंप्रेस करेगा और तेज़ थंबनेल बनाएगा। इससे स्टोरेज का उपयोग 90% तक कम हो जाता है और ऐप तेज़ हो जाता है।\n\nआपकी लाइब्रेरी के आकार के आधार पर इसमें एक मिनट लग सकता है।',
      'light_label': 'लाइट',
      'dark_label': 'डार्क',
      'low_label': 'कम',
      'high_label': 'उच्च',
      'delete': 'हटाएं',
      'recycle_bin': 'रीसायकल बिन',
      'empty_bin_title': 'रीसायकल बिन खाली करें?',
      'empty_bin_msg':
          'रीसायकल बिन के सभी दस्तावेज़ स्थायी रूप से हटा दिए जाएंगे। इस क्रिया को पूर्ववत नहीं किया जा सकता।',
      'perm_delete': 'स्थायी रूप से हटाएं',
      'undone_msg':
          'यह दस्तावेज़ हमेशा के लिए हटा दिया जाएगा। आप इस क्रिया को पूर्ववत नहीं कर सकते।',
      'doc_restored': 'दस्तावेज़ बहाल कर दिया गया',
      'pages': 'पेज',
      'protected': 'सुरक्षित',
      'rename': 'नाम बदलें',
      'export_doc': 'दस्तावेज़ निर्यात करें',
      'move_to_folder': 'फ़ोल्डर में ले जाएं',
      'document_tag': 'दस्तावेज़',
      'encrypted_tag': 'एन्क्रिप्टेड',
      'scan_tag': 'स्कैन',
      'user_label': 'उपयोगकर्ता',
      'loading': 'लोड हो रहा है...',
      'import_pdf': 'PDF आयात करें',
      'my_scanner': 'मेरा स्कैनर',
      'recent_captures': 'हालिया\nस्कैन',
      'search_hint': 'दस्तावेज़ खोजें...',
      'import_success': 'दस्तावेज़ सफलतापूर्वक आयात किया गया!',
      'import_failed': 'आयात विफल रहा',
      'no_docs_msg':
          'अभी तक कोई दस्तावेज़ नहीं है।\nशुरू करने के लिए एक स्कैन करें!',
      'no_match_msg': 'आपकी खोज से कोई\nदस्तावेज़ नहीं मिला।',
      'no_content_export': 'निर्यात करने के लिए कोई सामग्री नहीं है',
      'saved_to': '{0} में सहेजा गया',
      'export_failed': 'निर्यात विफल रहा: {0}',
      'moved_items': '{0} {1} स्थानांतरित किए गए',
      'move_failed': 'स्थानांतरण विफल रहा: {0}',
      'item_label': 'वस्तु',
      'items_label': 'वस्तुएं',
      'scan_button': 'दस्तावेज़ स्कैन करें',
      'sort_name': 'नाम',
      'sort_date': 'तारीख',
      'sort_modified': 'संशोधित',
      'sort_by': 'क्रमबद्ध करें: ',
      'grid_view': 'ग्रिड',
      'list_view': 'सूची',
      'perm_delete': 'स्थायी रूप से हटाएं',
      'undone_msg':
          'इस कार्रवाई को वापस नहीं लिया जा सकता। क्या आप सुनिश्चित हैं?',
      'empty_bin_title': 'रद्दी टोकरी खाली करें',
      'empty_bin_msg': 'सभी वस्तुओं को स्थायी रूप से हटाएं?',
      'recycle_bin': 'रद्दी टोकरी',
      'bin_empty_state': 'रद्दी टोकरी खाली है',
      'deleted_items_hint': 'हटाए गए दस्तावेज़ यहाँ दिखाई देंगे',
      'restore': 'बहाल करें',
      'delete_forever': 'हमेशा के लिए हटाएं',
      'folder_content': 'फोल्डर की सामग्री',
      'root_documents': 'मुख्य / मेरे दस्तावेज़',
      'incorrect_password_try_again': 'गलत पासवर्ड। कृपया पुनः प्रयास करें।',
      'check_out_doc': 'यह दस्तावेज़ देखें',
      'share_to_edit_label': 'संपादित करने के लिए साझा करें',
      'extracted_data_label': 'निकाला गया डेटा',
      'text_copied_snack': 'टेक्स्ट क्लिपबोर्ड पर कॉपी किया गया',
      'page_prefix': 'पेज',
      'protected_doc': 'सुरक्षित दस्तावेज़',
      'protected_doc_msg':
          'यह दस्तावेज़ एन्क्रिप्टेड है और इसे देखने के लिए पासवर्ड की आवश्यकता है।',
      'editable_word_doc_label': 'संपादन योग्य वर्ड दस्तावेज़',
      'share_to_edit_label': 'संपादित करने के लिए साझा करें',
      'extracted_data_label': 'निकाला गया डेटा',
      'split_pdf_tooltip': 'PDF विभाजित करें',
      'open_pdf_tooltip': 'अंतिम PDF खोलें',
      'share_doc_tooltip': 'दस्तावेज़ साझा करें',
      'microsoft_word_label': 'माइक्रोसॉफ्ट वर्ड',
      'ok_btn': 'ठीक है',
      'scanner_label': 'स्कैनर',
      'auto_label': 'ऑटो',
      'pdf_saved_library': 'पीडीएफ लाइब्रेरी में सहेजा गया!',
      'edit_text_title': 'टेक्स्ट संपादित करें',
      'sign_here_msg': 'यहाँ हस्ताक्षर करें',
      'clear_btn': 'साफ करें',
      'add_signature': 'हस्ताक्षर जोड़ें',
      'select_color': 'रंग चुनें',
      'page_of': 'पृष्ठ {0} का {1}',
      'merged_doc_prefix': 'मर्ज_दस्तावेज़',
      'split_batch_prefix': 'स्प्लिट बैच',
      'optimized_doc_prefix': 'अनुकूलित',
      'protected_doc_prefix': 'सुरक्षित',
      'confidential_label': 'गोपनीय',
      'watermarked_doc_prefix': 'वॉटरमार्केड',
      'repaired_doc_prefix': 'मरम्मत',
      'healthcheck_error_log': 'हेल्थचेक: संरचनात्मक भ्रष्टाचार का पता चला!',
      'idle': 'निष्क्रिय',
      'ready': 'तैयार',
      'unlocked_label': 'अनलॉक',
      'organized_doc_prefix': 'व्यवस्थित',
      'numbered_doc_prefix': 'क्रमांकित',
      'image_pdf_prefix': 'पीडीएफ',
      'signed_doc_prefix': 'हस्ताक्षरित',
      'pdf_to_text': 'PDF से टेक्स्ट',
      'pdf_text_extractor': 'PDF टेक्स्ट\nएक्सट्रैक्टर',
      'pdf_to_text_desc':
          'किसी भी PDF को तुरंत संपादन योग्य टेक्स्ट में बदलें।\nडेटा प्रविष्टि और सामग्री के पुनरुत्पादन के लिए आदर्श।',
      'no_text_extracted': 'इस PDF से कोई टेक्स्ट नहीं निकाला जा सका।',
      'save_extracted_text': 'निकाला गया टेक्स्ट सहेजें',
      'extraction_error': 'निष्कर्षण त्रुटि',
      'extracted_doc_prefix': 'निष्कर्षित',
      'copy_label': 'कॉपी',
      'copied_to_clipboard': 'क्लिपबोर्ड पर कॉपी किया गया',
      'select_from_library': 'लाइब्रेरी से चुनें',
      'no_pdfs_found_library': 'लाइब्रेरी में कोई PDF नहीं मिली',
      'pdf_library_hint':
          'उन्हें यहाँ देखने के लिए पहले छवियों या स्कैन को PDF में बदलें।',
      'open_pdf': 'PDF खोलें',
      'choose_doc_source': 'अपना\nदस्तावेज़ स्रोत चुनें',
      'open_pdf_hint':
          'अपने डिवाइस स्टोरेज से PDF चुनें या अपने मौजूदा स्कैन से एक संकलित करें।',
      'phone_storage': 'फ़ोन स्टोरेज',
      'phone_storage_hint': 'डाउनलोड, दस्तावेज़ और SD कार्ड में PDF खोजें',
      'internal_scans': 'आंतरिक स्कैन',
      'internal_scans_hint': 'इस ऐप से पहले कैप्चर किए गए दस्तावेज़ खोलें',
      'no_scans_found': 'कोई स्कैन नहीं मिला। पहले कुछ स्कैन करें!',
      'internal_library': 'आंतरिक लाइब्रेरी',
      'pdf_exports': 'PDF\nनिर्यात',
      'no_pdf_exports': 'अभी तक कोई PDF निर्यात नहीं हुआ',
      'pdf_exports_hint':
          'दस्तावेज़ों को स्कैन करें और उन्हें यहाँ सूचीबद्ध देखने के लिए निर्यात करें।',
      'id_card_prefix': 'पहचान_पत्र',
      'photo_session_label': 'सत्र',
      'adjust_edges': 'किनारों को ठीक करें',
      'enhancing': 'सुधार किया जा रहा है...',
      'opening_camera': 'कैमरा खोला जा रहा है...',
      'hold_steady_hint': 'सर्वोत्तम सटीकता के लिए कृपया स्थिर रहें',
      'rotate_label': 'घुमाएँ',
      'sort_modified': 'संशोधित',
      'privacy_policy': 'गोपनीयता नीति',
      'privacy_intro':
          'DocAction चुनने के लिए धन्यवाद। हम आपकी व्यक्तिगत जानकारी और गोपनीयता के आपके अधिकार की रक्षा के लिए प्रतिबद्ध हैं।',
      'privacy_h1': '1. जानकारी जो हम एकत्र करते हैं',
      'privacy_t1':
          'हम केवल वही जानकारी एकत्र करते हैं जो ऐप के कार्य करने के लिए आवश्यक है। इसमें शामिल हैं:\n• आपके द्वारा स्कैन किए गए दस्तावेज़ (आपके डिवाइस पर स्थानीय रूप से संग्रहीत)।\n• प्रोफ़ाइल जानकारी (नाम और प्रोफ़ाइल फ़ोटो) यदि आप उन्हें सेट करना चुनते हैं।\n• ऐप सेटिंग्स और प्राथमिकताएं।',
      'privacy_h2': '2. डेटा स्टोरेज',
      'privacy_t2':
          'आपके स्कैन किए गए दस्तावेज़ और चित्र आपके डिवाइस के आंतरिक स्टोरेज पर स्थानीय रूप से संग्रहीत होते हैं। हम आपके दस्तावेज़ों को किसी भी बाहरी सर्वर पर तब तक अपलोड नहीं करते जब तक कि आप स्पष्ट रूप से क्लाउड-सिंक सुविधा (यदि उपलब्ध हो) का उपयोग नहीं करते।',
      'privacy_h3': '3. अनुमतियां',
      'privacy_t3':
          'ऐप को कार्य करने के लिए निम्नलिखित अनुमतियों की आवश्यकता होती है:\n• कैमरा: भौतिक दस्तावेज़ों को स्कैन करने के लिए।\n• स्टोरेज: आपके स्कैन किए गए फ़ाइलों को सहेजने और लोड करने के लिए।\n• बायोमेट्रिक्स: ऐप लॉक के साथ ऐप को सुरक्षित करने के लिए।',
      'privacy_h4': '4. डेटा सुरक्षा',
      'privacy_t4':
          'हम आपके डेटा की सुरक्षा को गंभीरता से लेते हैं। फ़ाइलों को स्थानीय रूप से संग्रहीत करके और ऐप लॉक और पीडीएफ एन्क्रिप्शन जैसी सुविधाओं की पेशकश करके, हम यह सुनिश्चित करते हैं कि आप अपनी संवेदनशील जानकारी पर पूर्ण नियंत्रण में रहें।',
      'privacy_h5': '5. इस नीति में परिवर्तन',
      'privacy_t5':
          'हम समय-समय पर अपनी गोपनीयता नीति को अपडेट कर सकते हैं। हम इस पृष्ठ पर नई गोपनीयता नीति पोस्ट करके आपको किसी भी बदलाव के बारे में सूचित करेंगे।',
      'privacy_h6': '6. हमसे संपर्क करें',
      'privacy_t6':
          'यदि आपके पास इस गोपनीयता नीति के बारे में कोई प्रश्न हैं, तो कृपया हमसे devopsaksentt@gmail.com पर संपर्क करें',
      'scan_prompt': 'आप क्या स्कैन करना चाहेंगे?',
      'scan_sub': 'सर्वोत्तम परिणामों के लिए एक मोड चुनें',
      'mode_photo': 'फोटो',
      'mode_id_card': 'आईडी कार्ड',
      'mode_document': 'दस्तावेज़',
      'mode_ocr': 'ओसीआर',
      'mode_qr': 'क्यूआर कोड',
      'mode_signature': 'हस्ताक्षर',
      'english_label': 'अंग्रेजी',
      'hindi_label': 'हिंदी',
      'pick_word_storage': 'डिवाइस स्टोरेज से वर्ड फाइल चुनें',
      'choose_saved_word': 'अपने सहेजे गए दस्तावेजों में से चुनें',
      'not_word_file_error': 'चुनी गई फाइल वर्ड डॉक्यूमेंट नहीं है',
      'select_word_doc': 'वर्ड डॉक्यूमेंट चुनें',
      'word_doc_default_name': 'वर्ड_कनवर्टेड_{0}_{1}_{2}',
      'save_pdf_doc_title': 'पीडीएफ डॉक्यूमेंट सहेजें',
      'assign_converted_name_hint': 'अपने बदले हुए दस्तावेज़ को एक नाम दें',
      'converting_msg': 'वर्ड से पीडीएफ में बदला जा रहा है...',
      'success_saved_lib': 'सफल! लाइब्रेरी में सहेजा गया।',
      'word_convert_error': 'बदलना विफल रहा: {0}',
      'folder_content': 'फोल्डर कंटेंट',
      'back_to_library': 'लाइब्रेरी में वापस जाएं',
      'rename_doc': 'दस्तावेज़ का नाम बदलें',
      'enter_new_name': 'नया नाम दर्ज करें',
      'move_to_folder': 'फोल्डर में ले जाएं',
      'root_documents': 'मुख्य लाइब्रेरी',
      'delete_forever': 'हमेशा के लिए हटा दें',
      'add_from_scan': 'स्कैन से जोड़ें',
      'no_scans_found': 'लाइब्रेरी में कोई स्कैन नहीं मिला',
      'select_images_library': 'लाइब्रेरी से चित्र चुनें',
      'no_images_in_doc': 'इस दस्तावेज़ में कोई चित्र नहीं है',
      'edit_page': 'पेज संपादित करें',
      'select_source': 'स्रोत चुनें',
      'from_device': 'डिवाइस से',
      'from_device_sub': 'आंतरिक स्टोरेज से फाइल चुनें',
      'from_library': 'लाइब्रेरी से',
      'from_library_sub': 'स्कैन किए गए दस्तावेजों से चुनें',
      'extraction_quality': 'निष्कर्षण गुणवत्ता',
      'standard_label': 'मानक',
      'fast_conversion': 'तेज़ रूपांतरण',
      'hd_label': 'एचडी',
      'great_balance': 'उत्तम संतुलन',
      'ultra_label': 'अल्ट्रा',
      'print_ready': 'प्रिंट के लिए तैयार',
      'extract_as_images': 'चित्र के रूप में निकालें',
      'images_from_label': '{0} से चित्र',
      'extract_success_snack': 'सफलतापूर्वक {0} चित्र निकाले गए!',
      'extract_error_snack': 'निष्कर्षण त्रुटि: {0}',
      'init_conversion': 'रूपांतरण शुरू हो रहा है...',
      'extracted_page': 'निकाला गया पेज {0}',
      'extracted_images_count_log': 'PDF से {0} चित्र निकाले गए',
      'pdf_text_extractor': 'पीडीएफ टेक्स्ट एक्सट्रैक्टर',
      'pdf_to_text_desc':
          'किसी भी पीडीएफ दस्तावेज़ से टेक्स्ट डेटा जल्दी और सटीक रूप से निकालें।',
      'select_pdf': 'पीडीएफ चुनें',
      'pick_pdf_hint': 'डिवाइस से दस्तावेज़ चुनें',
      'select_file': 'फाइल चुनें',
      'pick_file_hint': 'कोई भी दस्तावेज़ या चित्र चुनें',
      'select_doc_library': 'लाइब्रेरी से चुनें',
      'any_to_word_desc':
          'पीडीएफ, चित्र और टेक्स्ट फाइलों को संपादन योग्य वर्ड (.docx) में बदलें।',
      'document_label': 'दस्तावेज़',
      'select_pdf_doc': 'पीडीएफ दस्तावेज़ चुनें',
      'no_text_extracted': 'इस पीडीएफ से कोई टेक्स्ट नहीं निकाला जा सका।',
      'extraction_error': 'निष्कर्षण त्रुटि',
      'extracted_doc_prefix': 'निकाला गया',
      'save_extracted_text': 'निकाला गया टेक्स्ट सहेजें',
      'doc_name_label': 'दस्तावेज़ का नाम',
      'filename_hint': 'फाइल का नाम',
      'save_success': 'सफलतापूर्वक सहेजा गया!',
      'error_saving': 'सहेजने में त्रुटि',
      'pdf_to_text': 'पीडीएफ से टेक्स्ट',
      'copied_to_clipboard': 'क्लिपबोर्ड पर कॉपी किया गया',
      'copy_label': 'कॉपी',
      'save_label': 'सहेजें',
      'pdf_to_word': 'पीडीएफ से वर्ड',
      'pdf_to_word_desc':
          'अपने पीडीएफ दस्तावेजों को संपादन योग्य वर्ड फाइलों (.docx) में बदलें।',
      'conversion_success': 'रूपांतरण सफल',
      'conversion_error_snack': 'रूपांतरण त्रुटि: {0}',
      'share_word_doc': 'वर्ड डॉक्यूमेंट साझा करें',
      'convert_another': 'दूसरा बदलें',
      'conversion_complete': 'रूपांतरण पूरा हुआ',
      'source_file': 'स्रोत फाइल',
      'pages_label': 'पेज',
      'converted_label': 'परिवर्तित',
      'converted_word_doc': 'परिवर्तित वर्ड डॉक्यूमेंट',
      'share_error_snack': 'साझा करने में त्रुटि: {0}',
      'saved_to_app_snack': 'ऐप स्कैन में सहेजा गया',
      'error_saving_snack': 'सहेजने में त्रुटि: {0}',
      'save_to_library': 'लाइब्रेरी में सहेजें',
      'text_preview': 'टेक्स्ट प्रीव्यू',
      'word_doc_no_preview':
          'मूल DOCX फाइलों के लिए वर्ड दस्तावेज़ प्रीव्यू उपलब्ध नहीं है।',
      'select_device': 'डिवाइस से चुनें',
      'select_device_sub': 'आंतरिक स्टोरेज से पीडीएफ चुनें',
      'select_app': 'ऐप से चुनें',
      'select_app_sub': 'अपने स्कैन किए गए दस्तावेजों से चुनें',
      'error_preparing': 'दस्तावेज़ तैयार करने में त्रुटि: {0}',
      'error_loading_pdf': 'पीडीएफ लोड करने में त्रुटि: {0}',
      'watermark_empty': 'वॉटरमार्क टेक्स्ट खाली नहीं हो सकता',
      'select_wm_image': 'कृपया पहले वॉटरमार्क इमेज चुनें',
      'saved_library_msg': 'वॉटरमार्केड पीडीएफ लाइब्रेरी में सहेजा गया',
      'error_generating_wm': 'वॉटरमार्क बनाने में त्रुटि: {0}',
      'stamp_doc': 'दस्तावेजों पर स्टैम्प लगाएं',
      'stamp_hint':
          'अपनी पीडीएफ फाइलों में तुरंत पेशेवर टेक्स्ट या इमेज वॉटरमार्क जोड़ें।',
      'select_pdf_file': 'पीडीएफ फाइल चुनें',
      'text_label': 'टेक्स्ट',
      'image_label': 'इमेज',
      'watermark_text_hint': 'वॉटरमार्क टेक्स्ट',
      'select_logo': 'लोगो/इमेज चुनें',
      'change_image': 'इमेज बदलें',
      'position_label': 'स्थिति',
      'diagonal': 'विकर्ण (Diagonal)',
      'center_label': 'केंद्र',
      'top_l': 'ऊपर बाएं',
      'top_r': 'ऊपर दाएं',
      'bottom_l': 'नीचे बाएं',
      'bottom_r': 'नीचे दाएं',
      'incorrect_password': 'गलत पासवर्ड। कृपया पुनः प्रयास करें।',
      'rotate': 'घुमाएँ',
      'error_prefix': 'त्रुटि',
      'doc_saved_success': 'दस्तावेज़ सफलतापूर्वक सहेजा गया!',
      'manage_document': 'दस्तावेज़ व्यवस्थित करें',
      'add_page': 'पेज जोड़ें',
      'no_scanned_images': 'कोई स्कैन की गई इमेज नहीं',
      'remove_page': 'पेज हटाएं',
      'open_label': 'खोलें',
      'view_image': 'इमेज देखें',
      'error_loading_image': 'इमेज लोड करने में त्रुटि',
      'browse_files': 'अपनी लोकल फाइलें ब्राउज़ करें',
      'system_photos': 'गैलरी से चित्र चुनें',
      'my_scans': 'मेरे स्कैन',
      'internal_app_scans': 'स्कैन किए गए दस्तावेजों से चुनें',
      'select_scans': 'स्कैन चुनें',
      'enter_password_hint': 'पासवर्ड दर्ज करें',
      'enter_name': 'नाम दर्ज करें',
      'incorrect_password': 'गलत पासवर्ड। कृपया पुनः प्रयास करें।',
    },
  };

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
